### ISSUE TITLE
gui: Remove unused `Decrypt` wallet

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin-core/gui#1]
The Decrypt case is unused and should be removed. See

```
src/qt/askpassphrasedialog.h:        Decrypt     /**< Ask passphrase and decrypt wallet */
```

#### Want to work on this issue?

For guidance on contributing, please read [CONTRIBUTING.md](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md) before opening your pull request.

**Comment by sehyunc** [comment]
Hey MarcoFalke, I'm interested in working on this issue.

**Comment by hebasto** [comment]
@sehyunc 
> Hey MarcoFalke, I'm interested in working on this issue.

Thanks! Will review your PR :)

**Comment by michaelfolkson** [comment]
Have you made any progress on this @sehyunc?

**Comment by sehyunc** [comment]
> Have you made any progress on this @sehyunc?

Hello, yes, I've spent some time familiarizing myself with the code base and working on this issue.

**Comment by hebasto** [comment]
@MarcoFalke Mind looking into #109 ?
