### ISSUE TITLE
Use random free port for test_bitcoin-qt

### ISSUE THREAD

**Issue by achow101** [bitcoin-core/gui#10]
Currently the `test_bitcoin-qt` unit test uses the standard regtest port. It will fail to start if something else is using the regtest port, like a regtest instance of bitcoind or bitcoin-qt. Or another running `test_bitcoin-qt` (this happens if you are updating multiple branches at the same time). Instead of using the standard regtest port, this unit test should be using a random free port like we do in the functional tests.

#### Want to work on this issue?

For guidance on contributing, please read [CONTRIBUTING.md](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md) before opening your pull request.

**Comment by dongcarl** [comment]
I think you're able to let the system assign one if you use port 0

**Comment by promag** [comment]
Concept ACK, also @dongcarl 👍
