### ISSUE TITLE
Use black icon for bitcoin-core account

### ISSUE THREAD

**Issue by Bosch-0** [bitcoin-core/gui#100]
Currently the account that hosts this repo and several others uses the orange bitcoin icon which (as far as I'm concerned) is the Bitcoin brand icon not the Bitcoin Core brand icon. Would it not be more on-brand to use the black icon for this account and orange Bitcoin icon for the bitcoin account? A discussions was had several weeks ago around branding here https://github.com/bitcoin-core/gui/issues/89

[Here](https://www.figma.com/file/4dO1LqPY0WAgp5d1Bz3U8j/Bitcoin-Core-Designs?node-id=16%3A15) is the black icon on a Figma that can be exported and used.

Visualized below before / after:

![Group 113](https://user-images.githubusercontent.com/55287964/95337707-b65c4c80-08e4-11eb-8bde-6892f5a12ff2.png)

This icon also has the 'B' filled white (the current icon is not filled) which looks slightly better when, for e.g. content is shared on twitter.  

![image](https://user-images.githubusercontent.com/55287964/95329863-36c98000-08da-11eb-8e47-a25320bd84cc.png)

Posted an issue over at https://github.com/bitcoin/bitcoin/issues/20098 regarding changing the black icon to orange for the bitcoin account.

**Comment by GBKS** [comment]
ACK

**Comment by MarcoFalke** [comment]
Is figma better than an SVG https://github.com/bitcoin/bitcoin/pull/16571/files#diff-ae926a4501336e7914755a32cc3af751 ?

**Comment by Bosch-0** [comment]
Figma is just an editor, you can export the logo I linked to as an SVG, PNG, JPG etc. apologies I missed this pull.

**Comment by johnsBeharry** [comment]
ACK

---

_"Consistency over correctness"_ as I've been told.

**Comment by Bosch-0** [comment]
Both of these repos should use this icon based on discussions here https://github.com/bitcoin-core/gui/issues/89

![Bitcoin Core Logo](https://user-images.githubusercontent.com/55287964/104463344-9e375000-55ec-11eb-8057-e6e3a3616ec7.png)

[Source](https://www.figma.com/file/0oqnohjahRtprjRyaetDOL/Bitcoin-Core-Design-System?node-id=1851%3A135)

**Comment by Bosch-0** [comment]
Closing this issue based on my comment above.
