### ISSUE TITLE
Drop workaround for fixed QTBUG-42503

### ISSUE THREAD

**Issue by hebasto** [bitcoin-core/gui#101]
In the code
https://github.com/bitcoin-core/gui/blob/9dd4de2832e298398436b957375d62de67f0a928/src/qt/overviewpage.cpp#L128

we should drop the workaround for [QTBUG-42503](https://bugreports.qt.io/browse/QTBUG-42503) which is already fixed since Qt 5.5.0.

Disclaimer: I'm not able to test a patch as testing requires retina display.

**Comment by prusnak** [comment]
PR in https://github.com/bitcoin-core/gui/pull/189

**Comment by jonasschnelli** [comment]
I keep this PR open since we still use a `QPushButton` for those icons (rather than a `QLabel`).

**Comment by prusnak** [comment]
How should a QLabel with an icon work?

Via the html img hack?

``` C
QLabel("<html><img src=':/resource.png'></html>")
```

Or should we use 2 QLabels for each QPushButton (one with an icon, the other with a text)?

**Comment by jonasschnelli** [comment]
AFAIK you can just use `QLabel::setPixmap()` (along with `setText()`).

**Comment by laanwj** [comment]
I am fairly sure you need two labels in that case, one with the pixmap one with the text. Otherwise, the label doesn't know how you want to position the icon and text relative to each other.

When it's possible to avoid using HTML that's generally preferable.

**Comment by prusnak** [comment]
I also think it's not possible to set both icon and text for a label.

Here's the trick how to solve it via VBoxLayout containing two labels https://forum.qt.io/topic/64020/settext-and-setpixmap-using

```
QWidget * container = new QWidget(this);
QVBoxLayout * layout = new QVBoxLayout(container);
QLabel * textLabel = new QLabel(container);
QLabel * imageLabel = new QLabel(container);

layout->addWidget(imageLabel);
layout->addWidget(textLabel);

imageLabel->setPixmap(...);
textLabel->setText(...);
```

Honestly, I am not so sure that's better than using a QPushButton

**Comment by jonasschnelli** [comment]
Let's keep the QPushButton then. Closing.
