### ISSUE TITLE
Requesting an "Accessibility" label for PRs

### ISSUE THREAD

**Issue by RandyMcMillan** [bitcoin-core/gui#103]
It may be useful to add an "Accessibility" label to the repo.
Having an "Accessibility" label would allow for better filtering of this particular type of work.

Wikipedia defines "Accessibility" as: [https://en.wikipedia.org/wiki/Accessibility](https://en.wikipedia.org/wiki/Accessibility)

Accessibility in the sense considered here refers to the design of products, devices, services, or environments so as to be usable by people with disabilities. The concept of accessible design and practice of accessible development ensures both "direct access" (i.e. unassisted) and "indirect access" meaning compatibility with a person's assistive technology (for example, computer screen readers).

QT defines "Accessibility" as: [https://doc.qt.io/Qt-5/accessible.html](https://doc.qt.io/Qt-5/accessible.html)

Accessibility in computer software is making applications usable for people with different abilities. It is important to take different people's needs into account, for example, in case of low vision, hearing, dexterity, or cognitive problems. Some examples of accessibility measures are keyboard shortcuts, a high-contrast user interface that uses specially selected colors and fonts, or support for assistive tools such as screen readers and braille displays.

**Comment by Sjors** [comment]
Sounds good. We sometimes have PR's dealing with keyboard access (e.g. https://github.com/bitcoin/bitcoin/pull/14810), but there's room for improvement.

**Comment by laanwj** [comment]
Yes, makes a lot of sense, thanks for the suggestion. I've added the label. If there's anything existing that needs to be tagged let me know.
