### ISSUE TITLE
Default window size in Ubuntu 200% (HiDPI) mode is wrong

### ISSUE THREAD

**Issue by jonasschnelli** [bitcoin-core/gui#104]
Starting Bitcoin-Qt on Ubuntu 20.04.01 with display scale of 200% results in a extremely tiny main window.

<img width="444" alt="Bildschirmfoto 2020-10-23 um 12 50 45" src="https://user-images.githubusercontent.com/178464/96995447-88a31480-152e-11eb-8701-0d9de9e61468.png">

**Comment by MarcoFalke** [comment]
Can reproduce on Fedora as well

**Comment by hebasto** [comment]
@jonasschnelli @MarcoFalke Mind testing #107 ?

**Comment by Bosch-0** [comment]
200% (HiDPI) on Windows also has issues on master https://github.com/bitcoin-core/gui/commit/9af7c1993b3512a7230f723b1923abd496989c59. Will test https://github.com/bitcoin-core/gui/pull/107

![image](https://user-images.githubusercontent.com/55287964/97265883-5d883000-1862-11eb-977e-24eaa8a829d5.png)

**Comment by hebasto** [comment]
@Bosch-0 
> 200% (HiDPI) on Windows also has issues on master [9af7c19](https://github.com/bitcoin-core/gui/commit/9af7c1993b3512a7230f723b1923abd496989c59).

It is a different problem which deserves its own issue.
