### ISSUE TITLE
Newley created encrypted wallets can't use "Create new receiving address"

### ISSUE THREAD

**Issue by jonasschnelli** [bitcoin-core/gui#105]
Freshly created **encrypted** wallets do have the "Create new receiving address" Button disabled. Closing and reopening fixes the issue.

<img width="803" alt="Bildschirmfoto 2020-10-23 um 12 52 48" src="https://user-images.githubusercontent.com/178464/96995762-fd764e80-152e-11eb-8c3a-001cbd3b1e4a.png">

Added 0.21.0 milestone.

**Comment by hebasto** [comment]
@jonasschnelli Mind testing https://github.com/bitcoin/bitcoin/pull/20230 ?

**Comment by jm9151821** [comment]
I had this same issue and solved it by going to the console and inputting the 'getnewaddress' command , with that the button became enabled.
