### ISSUE TITLE
Proxy Icon Tooltip Text

### ISSUE THREAD

**Issue by Rspigler** [bitcoin-core/gui#111]
The Proxy Icon appears when a proxy is set up.  I believe the icon only shows if there are no clearnet connections.  (I unfortunately cannot test this right now because I do not have control of my firewall settings where I am and cannot set an incoming clearnet connection).  But maybe, the icon shows regardless of other connections? (If so, that should be another discussion).

Please see https://github.com/bitcoin-core/gui/pull/86#issuecomment-715496157 for the discussion.

My point being, maybe we should change the Proxy Icon Tooltip Text from "Proxy is enabled" to something like "Connections are currently behind a Proxy" - like I think we will be doing for the Tor Icon Tooltip Text.

The use case is for something like if `proxy=127.0.0.1:9050` and `listen=1` is set (against default), but clearnet incoming connections have not been made yet. We wouldn't want users to think that, although the connections are currently marked secure, that they will forever be secured.

See #110  for an issue for better configuration of the settings.

**Comment by Rspigler** [comment]
Further conversations have taken discussion towards icons/GUI switches indicating current&future status, which I believe is better as well.

**Comment by thantkyaw1** [comment]
open

**Comment by thantkyaw1** [comment]
> The Proxy Icon appears when a proxy is set up. I believe the icon only shows if there are no clearnet connections. (I unfortunately cannot test this right now because I do not have control of my firewall settings where I am and cannot set an incoming clearnet connection). But maybe, the icon shows regardless of other connections? (If so, that should be another discussion).
> 
> Please see [#86 (comment)](https://github.com/bitcoin-core/gui/pull/86#issuecomment-715496157) for the discussion.
> 
> My point being, maybe we should change the Proxy Icon Tooltip Text from "Proxy is enabled" to something like "Connections are currently behind a Proxy" - like I think we will be doing for the Tor Icon Tooltip Text.
> 
> The use case is for something like if `proxy=127.0.0.1:9050` and `listen=1` is set (against default), but clearnet incoming connections have not been made yet. We wouldn't want users to think that, although the connections are currently marked secure, that they will forever be secured.
> 
> See #110 for an issue for better configuration of the settings.

Open
