### ISSUE TITLE
Main window default size unreasonable

### ISSUE THREAD

**Issue by luke-jr** [bitcoin-core/gui#113]
I think this was caused by the removal of the default wallet:
![Screenshot_20201024_092308](https://user-images.githubusercontent.com/1095675/97082859-37f9ed00-15fc-11eb-81e6-4114764ca9a2.png)

**Comment by hebasto** [comment]
Is #104 the same?

**Comment by luke-jr** [comment]
Probably, but it's not HiDPI-related.

**Comment by hebasto** [comment]
Fixed in #116.

**Comment by hebasto** [comment]
Unfortunately, on master (02cf20b9f571474c939d18a8b9d6b5d22479a222) I can seem a similar (the same?) issue on Fedora 33 + Qt 5.15.2:
```
$ src/qt/bitcoin-qt -regtest -printtoconsole
QSocketNotifier: Can only be used with threads started with QThread
2020-12-26T22:34:10Z Bitcoin Core version v21.99.0-02cf20b9f (release build)
2020-12-26T22:34:10Z Qt 5.15.2 (dynamic), plugin=wayland (dynamic)
2020-12-26T22:34:10Z System: Fedora 33 (Workstation Edition), x86_64-little_endian-lp64
2020-12-26T22:34:10Z Screen: Virtual-1 1920x1200, pixel ratio=1.0
...
```
![Screenshot from 2020-12-27 00-36-53](https://user-images.githubusercontent.com/32963518/103160281-aa916f80-47db-11eb-8347-8a8edb2a87fd.png)

**Comment by jonasschnelli** [comment]
The Bitcoin Core GUI (Qt) stores the window size and position. So I guess it could have been the problem in your case (@hebasto).

**Comment by hebasto** [comment]
> The Bitcoin Core GUI (Qt) stores the window size and position. So I guess it could have been the problem in your case (@hebasto).

I suspect that [that](https://github.com/bitcoin-core/gui/issues/113#issuecomment-751403151) were old Qt settings in my test VM.

**Comment by thantkyaw1** [comment]
Opend this issue on to day
