### ISSUE TITLE
Change sync bar to % synchronized / time left until complete

### ISSUE THREAD

**Issue by Bosch-0** [bitcoin-core/gui#124]
A minor UX improvement. 

Having the network sync progress bar at the bottom of the GUI display a **% synchronized / time left until complete** would be more relevant information to display here than the current, more abstract 'weeks/years behind.' 

Weeks/years behind is likely to confuse users - the questions that pops into my head when attempting to view this as a beginner are "what does that mean?" whereas a simple % synchronized / time left until complete is quite clear and tells the user what they need to know. Additionally, this is how other node products display their node status so users are likely more familiar with this. 

Change visualized below:
![Frame 1](https://user-images.githubusercontent.com/55287964/97548994-d1653c80-1a0a-11eb-8d4f-71d90fc764d0.png)

Users can still see how many weeks they are behind by bringing up the node modal if they wish.

**Comment by johnsBeharry** [comment]
Concept ACK

**Comment by jarolrod** [comment]
Concept ACK

Completely agree. I would switch around the position of these metrics so that it is (Time Left)(% Synchronized)

**Comment by Bosch-0** [comment]
> I like how knowing how far behind my node is, but at a glance by primary interest would be in how long the download is estimated to take.

Yep for sure! If you click on the sync bar you can still see how far behind it is 👍

**Comment by Rspigler** [comment]
Concept ACK

**Comment by hebasto** [comment]
This approach will be duplicate data that are presented to users:

![DeepinScreenshot_select-area_20210305025345](https://user-images.githubusercontent.com/32963518/110051243-25d44c00-7d5e-11eb-9d6e-e664abbe75ff.png)

**Comment by Rspigler** [comment]
Very good point.  I guess my only comment would be, there isn't any duplicate data if a user selects `Hide`, and do they then know how to bring that window back up? (You just have to click on the sync bar, so shouldn't be too difficult)

**Comment by Bosch-0** [comment]
The progress option / estimated time left could be removed from the overlay so it's only shown in the bottom menu.

**Comment by hebasto** [comment]
@Bosch-0 
> The progress option / estimated time left could be removed from the overlay so it's only shown in the bottom menu.

How the overlay should look like in this case?

What are benefits for UX (not arguing, curios)?

**Comment by Bosch-0** [comment]
> What are benefits for UX (not arguing, curios)?

Knowing if your node is synced up the latest block is relevant info users should be able quickly digest when opening the GUI. The less clicks a user has to take to get this information the better - they shouldn't have to open an overlay to view this. It doesn't need to be included in the overlay as its just repeating the same details.

Mockup below with changes stated at start of this issue + overlay: 

![Frame 2](https://user-images.githubusercontent.com/55287964/112792530-398d7c80-9096-11eb-97f4-db0f19d9969c.png)

**Comment by rebroad** [comment]
How accurate is the percentage we're currently getting? Is it linear to the time needed/taken?

**Comment by CR6461** [comment]
good information...

**Comment by katesalazar** [comment]
up for grabs?

**Comment by hebasto** [comment]
Closing due to a long period of inactivity here. Feel free to reopen.

Also labeled it with "Up for grabs".
