### ISSUE TITLE
error message is empty when no translation is available

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin-core/gui#128]
Steps to reproduce:

```
$ ./src/qt/bitcoin-qt -regtest -datadir=/tmp
... Create sqlite wallet "load"
... Stop program
$ ./src/qt/bitcoin-qt -regtest -datadir=/tmp -wallet=/tmp/regtest/wallets/load/ -wallet=load
```

![Screenshot from 2020-11-04 13-52-33](https://user-images.githubusercontent.com/6399679/98114122-11ae3a00-1ea5-11eb-88e7-c678337ce6d5.png)

See also https://github.com/bitcoin/bitcoin/pull/20199#discussion_r517691457

**Comment by hebasto** [comment]
Fixed in https://github.com/bitcoin/bitcoin/pull/20308.
