### ISSUE TITLE
Translation shortcuts are incorrect, transifex strings have leading 'space' character

### ISSUE THREAD

**Issue by jarolrod** [bitcoin-core/gui#150]
Looking into how #129 would affect shortcuts in other languages, I noticed that many shortcuts are incorrect in other languages because the Transifex translation string contains a leading `space` character. I believe that a linter should be put in place to prevent this from happening in the future,

**Affected Translations:** ` bitcoin_ta.ts`, `bitcoin_ar.ts`, `bitcoin_uz@Cyrl.ts`, `bitcoin_sr.ts`, `bitcoin_ml.ts`, `bitcoin_es_CL.ts`,       `bitcoin_nl.ts`,  `bitcoin_ms.ts`, `bitcoin_lt.ts`, `bitcoin_es.ts`, `bitcoin_th.ts` `bitcoin_th.ts`, `bitcoin_te.ts`, `bitcoin_nb.ts`,  `bitcoin_id.ts`, `bitcoin_hi.ts`, `bitcoin_fil.ts`, `bitcoin_el.ts`, `bitcoin_bg.ts`

#### To Replicate: 
1) In order to `grep` the `*.ts` files we need to set them executable. Under `qt/src/locale`, run:
``` bash
chmod +x ./*.ts
```
2) now `grep` for a matching `&amp;` followed by a 'space' character
``` bash
grep -n "&amp; " ./*.ts
```

3) **Optional:** To get the files and number of occurrences (Sorted):
``` bash
grep -c "&amp; " ./*.ts | grep -v ':0$' | sort -n -k2 -t:

```

4) Below represents the output you will see. Here is a [pastebin link](https://pastebin.com/TGFmdLw0) of the full output. In this example, the shortcut for this command will be `space` instead of `G`. This is incorrect and needs to be addressed. 
``` bash 
 <translation>&amp; Gastar cambio no confirmado</translation>
```
5) Using the above example: If we take a look at the [transifex page](https://www.transifex.com/bitcoin/bitcoin/) we find that the string does in fact contain a leading `space` character when it is not supposed to.
![Screenshot_2020-12-11 bitcoin Transifex Editor](https://user-images.githubusercontent.com/23396902/101961860-a872c280-3bd8-11eb-8e08-5e7d65363948.png)

**Comment by thantkyaw1** [comment]
true open

**Comment by thantkyaw1** [comment]
@thantkyaw1 open
