### ISSUE TITLE
Bitcoin Core Transaction Fee recommedation is a fail:

### ISSUE THREAD

**Issue by s3cryptostuff** [bitcoin-core/gui#156]
I selected 20 minutes ( 2 blocks) as transaction fee. 7 hours later and not a single confirmation.
I now have .75 bitcoin sitting in neverland. This pay extortion fees to miners or your txs does not go through is extortion.
At least have the gui recommend a useful amount.

I sent with Electrum no problem

**Comment by hebasto** [comment]
Fee estimator is a probabilistic tool. You could find more details and ask additional questions about fee estimation on the [Bitcoin StackExchange](https://bitcoin.stackexchange.com) or the `#bitcoin` IRC channel on freenode.
