### ISSUE TITLE
Detail view shows disconnected peer's info

### ISSUE THREAD

**Issue by hebasto** [bitcoin-core/gui#158]
**To reproduce**

1) select the "Peer" tab in the "Node window"

2) choose any peer by clicking its row in the table, the detail view shows the peers's info

3) wait until the chosen peer disconnect 

**Expected behavior**

The detail view stops showing the disconnected peer's info (probably, show nothing).

**Actual behavior**

The detail view is still showing the disconnected peer's info that is wrong.

**System information**

Bitcoin Core 0.21.0rc3

Linux Mint 20

**Comment by hebasto** [comment]
cc @promag

**Comment by MarcoFalke** [comment]
Is this a regression?

**Comment by hebasto** [comment]
Hmm, cannot reproduce this issue on regtest connecting some nodes each to other.

**Comment by hebasto** [comment]
Ok, I've managed to reproduce it:
![Screenshot from 2020-12-22 12-01-47](https://user-images.githubusercontent.com/32963518/102876333-ba145f80-444d-11eb-9fa0-cc66b6599d5b.png)

**Comment by hebasto** [comment]
@MarcoFalke 
> Is this a regression?

No, it isn't. The 0.20.0 has the same behavior.

**Comment by hebasto** [comment]
Not observed on master due to the #13. But peer table logic is still broken if the table is sorted, see #18.

Closing.
