### ISSUE TITLE
Replace "Direction" with "Connection Type" in Peer Tab

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin-core/gui#159]
To give more detailed information about the connection type, the legacy type (direction) should be replaced by connection type

Current master:

![Screenshot from 2020-12-22 12-37-12](https://user-images.githubusercontent.com/6399679/102884777-81c35000-4452-11eb-916d-1b6a066df6e9.png)

**Comment by hebasto** [comment]
Maybe "good first issue" label?

**Comment by jonatack** [comment]
Was on my list this week at the same time as updating -netinfo

**Comment by jonatack** [comment]
along with adding the network field too
