### ISSUE TITLE
User Agent header flickers when trying to resize any column

### ISSUE THREAD

**Issue by hebasto** [bitcoin-core/gui#191]
![header_bug](https://user-images.githubusercontent.com/32963518/105186299-3cba3880-5b3a-11eb-92dc-42f408ce88da.gif)

System: Linux Mint 20.1 + Cinnamon DE + Qt 5.12.8

**Comment by jarolrod** [comment]
Confirming the same happens on macOS 11.1 + Qt 5.15.2

**Comment by RandyMcMillan** [comment]
Appending a "bumper" as the last column of the peertablemodel should fix this issue.

In this stale PR - I found that was a reasonable solution.

https://github.com/bitcoin-core/gui/pull/135/files#diff-e721b02fefce2a90ae95da0841adfdcc610ffccf93236ef236f81c1baead8e01R112

**Comment by hebasto** [comment]
> Appending a "bumper" as the last column of the peertablemodel should fix this issue.
> 
> In this stale PR - I found that was a reasonable solution.
> 
> https://github.com/bitcoin-core/gui/pull/135/files#diff-e721b02fefce2a90ae95da0841adfdcc610ffccf93236ef236f81c1baead8e01R112

@RandyMcMillan 
Could that change be separated from #135 into its own bugfix PR?

**Comment by RandyMcMillan** [comment]
I will take a look - the PR may be too stale.

**Comment by RandyMcMillan** [comment]
I should have a fix in a few minutes.

**Comment by hebasto** [comment]
@RandyMcMillan 
Another option is to fix the `TableViewLastColumnResizingFixer` class.

**Comment by hebasto** [comment]
Interesting that the `banlistWidget` has the same properties as the `peerWidget`, but the former works without flickering.

**Comment by hebasto** [comment]
It appears that this bug is fixed in f73d340abeedf7e583fe9b2a8b3685a745a9199e (#164).

@jarolrod Could you check it please?

**Comment by jarolrod** [comment]
@hebasto testing now

One note about this bug is that it happens if that `User Agent` column is a certain size. If I resize the `User Agent` column to be smaller, then it doesn't happen when I got to resize other columns. But, if I bring it back to its original size, the bug shows up.

![bug-gif](https://user-images.githubusercontent.com/23396902/105268249-d811d480-5b5f-11eb-807e-035866e70ddd.gif)

**Comment by jarolrod** [comment]
@hebasto confirming that #164 fixes this bug, seems that your refactoring of `PeerTableModel::refresh()` did the job
