### ISSUE TITLE
Disappearing progress bar with Qt 5.15.2

### ISSUE THREAD

**Issue by jarolrod** [bitcoin-core/gui#193]
The progress bar will disappear if you click on another non-bitcoin-qt window. This happens with Qt 5.15.2 on macOS. Could not replicate on macOS with Qt5.9.8 or with the binary releases.

**Bitcoin Qt Window In Focus**
<img width="426" alt="Screen Shot 2021-01-20 at 7 23 27 PM" src="https://user-images.githubusercontent.com/23396902/105279649-04385000-5b76-11eb-9462-9ac353b40a7f.png">

**Click on another window, Bitcoin Qt No longer in Focus**
<img width="407" alt="Screen Shot 2021-01-20 at 7 23 38 PM" src="https://user-images.githubusercontent.com/23396902/105279663-0f8b7b80-5b76-11eb-9b69-996c6cc3e386.png">

System: macOS 11.1, Qt 5.15.2

**Comment by hebasto** [comment]
Seems like an upstream bug. Could you test the Fusion style (#177)?

**Comment by hebasto** [comment]
It seems all off-focus widgets lose their highlight color, e.g., default buttons.

Other native macOS apps have the same behavior, e.g., file save dialog of the TextEdit.

It does not look as Qt bug.

**Comment by jarolrod** [comment]
@hebasto I recently noticed that as well, let me close.
