### ISSUE TITLE
Add ability to easily read the Bitcoin whitepaper from the GUI

### ISSUE THREAD

**Issue by ericallam** [bitcoin-core/gui#195]
The bitcoin whitepaper was removed recently from a prominent bitcoin website in response to a legal challenge from an idiot/scammer. Luckily, the whitepaper is embedded in the a transaction and can be read [with a little programming](https://bitcoin.stackexchange.com/questions/35959/how-is-the-whitepaper-decoded-from-the-blockchain-tx-with-1000x-m-of-n-multisi/35970#35970).

I'd like to be able to click a button (perhaps in the menu bar?) in the GUI that will automatically decode the whitepaper transaction and open the PDF in my default PDF reader.

I've considered doing a search for "Bitcoin Whitepaper" but I believe that is bad OpSec.

**Comment by jarolrod** [comment]
NACK, there's no need for this inside of the GUI.
