### ISSUE TITLE
Activate travis in this repo

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin-core/gui#2]
Ci should be active in this repo as well

**Comment by MarcoFalke** [comment]
Done

**Comment by hebasto** [comment]
> Done

Travis' job _"x86_64 Linux [GOAL: install] [bionic] [no depends, only system libs, sanitizers: address/leak (ASan + LSan) + undefined (UBSan) + integer]"_ reaches timeout: https://travis-ci.org/github/bitcoin-core/gui/jobs/699659959

**Comment by MarcoFalke** [comment]
@hebasto this is a general issue in travis with forked repos, unrelated to this repo. Proposed fix in https://github.com/bitcoin/bitcoin/pull/19321
