### ISSUE TITLE
"Label" for receiving addresses, and its position in context menu is misleading

### ISSUE THREAD

**Issue by surak** [bitcoin-core/gui#209]
Transactions have a field "label". It makes it look like each transaction can be labeled (which is bitcoin parlay seems to be a `comment`), when it's actually a label of the receiving address. This is misleading and can be clarified. 

This is not a new issue: https://github.com/bitcoin/bitcoin/pull/5905 , but a new but was created (and closed) on bitcoin-core about that recently: https://github.com/bitcoin/bitcoin/issues/21057

Even though a `comment` field would be very welcome, this issue here is simply about the confusion created by the understanding of the term label on the GUI.

**Actual behavior**

When one sets a label, it sets a label for the receiving address. It's not clear until the moment when one clicks "edit label" and a dialog appears what that means.

**To reproduce**

Right-click a transaction, choose "edit label" - it seems a unfortunate place for such a thing, since other menu items are for that transaction and not for the receiving address.

**System information**

Bitcoin-QT 0.21.0 for Mac OS.

**Comment by jonasschnelli** [comment]
Agree that this is confusing.
Would removing the "edit label" action in the transaction context menu be more an option? I guess one trying to edit the labels can still use the address books

**Comment by MarcoFalke** [comment]
Indeed, as a first step it could make sense to remove the per-tx "edit label" because it is really per-address. As a second step, https://github.com/bitcoin/bitcoin/pull/5905 could be rebased.

**Comment by jarolrod** [comment]
When you click `Edit Label` you are really editing the label for the address type. Looking at the code, the `Edit Label` action determines what the address type is and brings up the associated mechanism. If we are to remove the `Edit Label` action from the `transactionview`, we must ensure there's another way to edit the label

For a `Sending` address, you can currently edit the label in the `Address Book` of the send tab.

For a `Receiving Address`, it seems the only place to edit the label would be in the `transactionview` of the `Transactions` tab as the received address view lacks an `Edit Label` action in its context menu. An `Edit Label` action should be added to the `Receive` Tab.

**Comment by jarolrod** [comment]
Documenting that this issue is related to https://github.com/bitcoin/bitcoin/issues/1168

**Comment by MarcoFalke** [comment]
Fixed in #223
