### ISSUE TITLE
Error: This wallet has no available keys (code -4)

### ISSUE THREAD

**Issue by chaihahaha** [bitcoin-core/gui#218]
I created a new empty encrypted wallet and used walletpassphrase to unlock it and used importprivkey to import my private key.
Then I found that I still cannot create a new address. After entering getnewaddress, I get the error message "Error: This wallet has no available keys (code -4)".

I expected that I can create a new address.

'Create a new receiving address' is greyed out.

I used Bitcoin Core v0.21.0 downloaded from bitcoin.org, I got the error message in the console of Bitcoin Core GUI.

Windows 10.0.19042, Intel i7-4720HQ, HDD

**Comment by jarolrod** [comment]
Confirming that I can replicate this issue on macOS 11.1

Steps I took to Replicate:
- Create a new Encrypted wallet with `Make Blank Wallet` option selected. This option means that the wallet starts out with no private keys and you can add them in later with `importprivkey` or `sethdseed`
- Go over to console and unlock wallet with `walletpassphrase "123" 60`
- In console, run: `importprivkey <priv_key> "label"`
- Run `getnewaddress` -> get error: `Error: This wallet has no available keys (code -4)`

While `importprivkey` leads to this error, I can still populate the wallet with a key using `sethdseed` then subsequently create a new address.

**Comment by jarolrod** [comment]
I can also replicate using `bitcoind` and `bitcoin-cli`, the debug log says I already have this key in pubkey and already have the script. This is the same issue as outlined in https://github.com/bitcoin/bitcoin/issues/16711. Still cannot create a new address with `getnewaddress` after importing the private key

**Comment by hebasto** [comment]
@chaihahaha @jarolrod 

What is the result of the `getwalletinfo` command?

**Comment by jarolrod** [comment]
After importing a valid private key with `importprivkey` the `keypoolsize` is 0:
```
{
  "walletname": "new-wallet",
  "walletversion": 169900,
  "format": "bdb",
  "balance": 0.00000000,
  "unconfirmed_balance": 0.00000000,
  "immature_balance": 0.00000000,
  "txcount": 0,
  "keypoololdest": 1614066198,
  "keypoolsize": 0,
  "keypoolsize_hd_internal": 0,
  "paytxfee": 0.00000000,
  "private_keys_enabled": true,
  "avoid_reuse": false,
  "scanning": false,
  "descriptors": false
}
```

after running `sethdseed`, it successfully populates with a private key:
```

{
  "walletname": "new-wallet",
  "walletversion": 169900,
  "format": "bdb",
  "balance": 0.00000000,
  "unconfirmed_balance": 0.00000000,
  "immature_balance": 0.00000000,
  "txcount": 0,
  "keypoololdest": 1614066274,
  "keypoolsize": 1000,
  "hdseedid": "114871bad9b02312f198bbd5ebd852ae0614b855",
  "keypoolsize_hd_internal": 1000,
  "paytxfee": 0.00000000,
  "private_keys_enabled": true,
  "avoid_reuse": false,
  "scanning": false,
  "descriptors": false
}

```

**Comment by hebasto** [comment]
> I can also replicate using `bitcoind` and `bitcoin-cli` on master...

This issue should be posted in the [main repo](https://github.com/bitcoin/bitcoin/issues), I think.

**Comment by jarolrod** [comment]
This can be closed in favor of https://github.com/bitcoin/bitcoin/issues/21275
