### ISSUE TITLE
Make clickable elements look clickable -- warning symbol buttons on Overview screen

### ISSUE THREAD

**Issue by statusquont** [bitcoin-core/gui#23]
On the Overview panel there are 2 warning symbols: ⚠️ which would seem to indicate something of great importance to a user. But they don't currently provide any visual clue that they are actionable elements. If they had a more clickable-appearance (borders or beveled button edges) it could help users more quickly understand what they are being alerted to.

![image](https://user-images.githubusercontent.com/15948511/86392664-76405a80-bc61-11ea-9ef1-34be08ac12b0.png)

**Comment by Sjors** [comment]
I didn't even know they were clickable, so they can't be that important :-)

**Comment by hebasto** [comment]
@statusquont Would it be ok if those elements become buttons?

**Comment by polylunar** [comment]
I concur with @statusquont and think these warnings should be clickable. Also ok with the proposal of @hebasto to have them as buttons. Thanks.

**Comment by hebasto** [comment]
@polylunar 
> I concur with @statusquont and think these warnings should be clickable.

Currently, those GUI elements _are_ clickable already.
They not _look_ clickable though :)

**Comment by polylunar** [comment]
Yes, sorry, should've been clearer, it would be good for them to be better identifiable as clickable, thanks.
