### ISSUE TITLE
Issue with spaces with sentence containing commas and periods.

### ISSUE THREAD

**Issue by edumorlom** [bitcoin-core/gui#235]
I am seeing space issues after periods and commas in the "Welcome to Bitcoin Core" screen. See the screenshot attached.

Upon looking at the translation files, I don't see any immediate issues with the strings:
https://github.com/bitcoin-core/gui/blob/54fc96ffa70ad3a53d32709101b7a2ce064d822e/src/qt/forms/intro.ui

<img width="451" alt="Screen Shot 2021-03-02 at 10 51 53 AM" src="https://user-images.githubusercontent.com/11444894/109631154-f8ad5100-7b45-11eb-8222-af319ced62d1.png">

I am running macOS Big Sur.

**Comment by edumorlom** [comment]
Seems to be a global issue, maybe?

<img width="246" alt="Screen Shot 2021-03-02 at 11 01 20 AM" src="https://user-images.githubusercontent.com/11444894/109631890-b8020780-7b46-11eb-9969-fea99c760d89.png">

**Comment by hebasto** [comment]
Tested on Big Sur 11.2.2 (20D80) with a patch that allows select and copy the first paragraph:

```diff
--- a/src/qt/forms/intro.ui
+++ b/src/qt/forms/intro.ui
@@ -51,6 +51,9 @@
      <property name="wordWrap">
       <bool>true</bool>
      </property>
+     <property name="textInteractionFlags">
+      <set>Qt::LinksAccessibleByMouse|Qt::TextSelectableByMouse</set>
+     </property>
     </widget>
    </item>
    <item>
```

Then the selected text pasted into the TextEdit:
![Screenshot from 2021-03-02 17-19-19](https://user-images.githubusercontent.com/32963518/109670658-0087e800-7b7c-11eb-9443-df1416d6ed57.png)

Text is fine.

I think that the default macOS font issue is out of our scope.

**Comment by edumorlom** [comment]
Should we close the issue? @hebasto

**Comment by hebasto** [comment]
> Should we close the issue? @hebasto

Yes, I think.
