### ISSUE TITLE
Give primary action items more visual weight

### ISSUE THREAD

**Issue by statusquont** [bitcoin-core/gui#24]
The Receive panel indicates that "all fields are optional" and if that is indeed the case, there is no clear visual cues what the correct action is -- it's to click the 'Create New Receiving Address' button.

Suggestion: give primary action buttons an orange background.

![image](https://user-images.githubusercontent.com/15948511/86393166-43e32d00-bc62-11ea-980b-1d34a50f0d98.png)

Here's an example from GitHub settings where a UI has multiple actions, but they visually guide the user to the action they should be taking with a colored button.

![image](https://user-images.githubusercontent.com/15948511/86393666-fd420280-bc62-11ea-8e07-c261898aac0a.png)

**Comment by Sjors** [comment]
More emphasis on the primary action makes sense. I think there's a QT standard way of marking buttons as such:
<img width="983" alt="Schermafbeelding 2020-07-02 om 20 44 50" src="https://user-images.githubusercontent.com/10217/86397861-ec19e580-bca4-11ea-8ee3-935304420f03.png">

<img width="360" alt="Schermafbeelding 2020-07-02 om 20 45 52" src="https://user-images.githubusercontent.com/10217/86397929-0eabfe80-bca5-11ea-95b2-e20fa33a2ed7.png">

**Comment by hebasto** [comment]
@Sjors 
Unfortunately, on Linux it looks not such emphasized:

![Screenshot from 2020-07-11 11-22-27](https://user-images.githubusercontent.com/32963518/87220007-15073e00-c369-11ea-9a0a-9476f7095787.png)

**Comment by Sjors** [comment]
I see a subtle blue line around Hide. Can you show a screen with more than 1 button? Doing non-native styling can get real ugly real fast in my experience.

**Comment by hebasto** [comment]
@Sjors 
> I see a subtle blue line around Hide. Can you show a screen with more than 1 button?

Qt 5.9.8 (static):
![Screenshot from 2020-07-17 12-50-30](https://user-images.githubusercontent.com/32963518/87773759-492ca400-c82c-11ea-9f57-2b5bb3269fe1.png)

Qt 5.12.8 (dynamic):
![Screenshot from 2020-07-17 12-35-52](https://user-images.githubusercontent.com/32963518/87773864-6bbebd00-c82c-11ea-85da-0e316e8b9b91.png)

> Doing non-native styling can get real ugly real fast in my experience.

Agree.

**Comment by Sjors** [comment]
I think these are both clear enough, the static build (which we ship) is the most clear.

**Comment by hebasto** [comment]
> I think these are both clear enough, the static build (which we ship) is the most clear.
> 
> So in the original example, maybe we just need to mark the Receive button as primary?

Actually, in a such way not the "primary action" button highlighted rather the focused one.

**Comment by hebasto** [comment]
@statusquont 
Mind providing an example among desktop widget-based applications to find the solution without non-native styling?

**Comment by sixside** [comment]
I'm not sure if I understand what you're asking for, but hopefully this helps, from the GitHub Desktop application (Windows)

![image](https://user-images.githubusercontent.com/2085360/87891628-3a96e600-ca00-11ea-8e59-2fbe6e542a2f.png)

If I misunderstood the question, please advise.

**Comment by statusquont** [comment]
I'm not sure if I understand what you're asking for, but hopefully this helps, from the GitHub Desktop application (Windows).

![image](https://user-images.githubusercontent.com/15948511/87891724-8c3f7080-ca00-11ea-9a95-1035973417af.png)

If I misunderstood the question please advise.

**Comment by hebasto** [comment]
Concept ACK.

To implement this feature into the code (say, "primary push button") some _design_ decisions are required to make it harmonized with the used styles on all supported platforms.

It could be made as artworks, e.g., https://doc.qt.io/qt-5/gallery.html

> Doing non-native styling can get real ugly real fast in my experience.

That is it what we should avoid for sure.

**Comment by statusquont** [comment]
Yeah, that makes a lot of sense. IMO a good design should be there to help a user make decisions, but other than that, get out of the way and don't cause distraction. 

I'm not too familiar with QT, but I would presume (and hope) that efforts have been made in that project to consider usability for all types of users (including vision impaired for example) and design the UI accordingly. So leaning on QT's prior work makes a lot of sense. In that regard, I'll retract my previous suggestion of "give primary action buttons an orange background" since that seems to be outside of the scope at this time. Perhaps it can be revisited at a later time as the [Bitcoin Design working group](https://github.com/BitcoinDesign) make further progress to establish a set of visual standards.

To wrap this issue up, I'd just ask whether or not the 'Create New Receiving Address' button is inheriting the default button push properties from QT in order to help the user make a decision?
https://doc.qt.io/qt-5/qpushbutton.html#default-prop

I'm not sure where/how to check the code to answer this question myself.

**Comment by hebasto** [comment]
@statusquont 
> To wrap this issue up, I'd just ask whether or not the 'Create New Receiving Address' button is inheriting the default button push properties from QT in order to help the user make a decision?
> https://doc.qt.io/qt-5/qpushbutton.html#default-prop
> 
> I'm not sure where/how to check the code to answer this question myself.

Mind testing #39 ?

**Comment by statusquont** [comment]
Looks improved, slightly, but still an improvement nonetheless! 👍

**Comment by statusquont** [comment]
Not sure of proper protocol here. Do I close this issue? Or does it auto-close once #39 gets closed?

**Comment by hebasto** [comment]
> Not sure of proper protocol here. Do I close this issue? Or does it auto-close once #39 gets closed?

The latter one :)
