### ISSUE TITLE
Default sorting of transaction list gets confused

### ISSUE THREAD

**Issue by laanwj** [bitcoin-core/gui#244]
Opening an old wallet with a fairly large number of transactions it comes up like this:

![screenshot_btc_dates](https://user-images.githubusercontent.com/126646/110656749-87fada00-81c0-11eb-8618-dc34fca3ecb1.png)

Although the 'date' column is checked, it doesn't look like sorted by date at all. After clicking twice on the column header it does sort it by date correctly.

This is with:
- Current master as of 7cdadf91d513250b983b6a1c4672a6acc0dcf074
- Ubuntu 20.04 (Focal) system Qt — 5.12.8+dfsg-0ubuntu1

**Comment by jarolrod** [comment]
This was reported as an issue before somewhere in the Core repo, hebasto has a PR to fix this: https://github.com/bitcoin-core/gui/pull/229
