### ISSUE TITLE
Pruning should be based on bitcoin.conf

### ISSUE THREAD

**Issue by prayank23** [bitcoin-core/gui#245]
![image](https://user-images.githubusercontent.com/13405205/110880766-23956300-8305-11eb-8fec-a64e00bc3530.png)

Its mentioned that options set in GUI will be overridden by the configuration file. I had nothing for mainnet in `bitcoin.conf`, removed `testnet=1` and `prune=555` for testnet, saved new `datadir` path for external drive that had mainnet synced.

I launched `bitcoin-qt` assuming it will not prune anything because there is nothing mentioned in `bitcoin.conf`, it deleted all my data and pruning was done based on GUI options which had 2 GB saved either by default or maybe I saved it in past.

**Expected behavior**

If `bitcoin.conf` does not mention anything about pruning it should not prune. If GUI for mainnet had pruning enabled in GUI, it should be saved automatically in `bitcoin.conf` as well to avoid the confusion and things remain in sync.

**Actual behavior**

Pruning is done based on GUI options

**To reproduce**

Sync a full node. Maybe testnet which will take less time.

Use the blocks and chainstate in other node (which had pruning enabled in GUI) using `datadir` and `bitcoin.conf` doesn't have anything else.

Launch `bitcoin-qt`

**System information**

Bitcoin Core v 0.21.0. Ubuntu 20.04.2 LTS.

**Comment by hebasto** [comment]
@prayank23 
> If GUI for mainnet had pruning enabled in GUI, it should be saved automatically in `bitcoin.conf` as well to avoid the confusion and things remain in sync.

It is a common consensus that, for safety, the opposite seems correct. From [`doc/files.md`](https://github.com/bitcoin/bitcoin/blob/master/doc/files.md):
> File is not written to by the software and must be created manually.

**Comment by prayank23** [comment]
@hebasto How about adding a confirmation window before this pruning begins based on GUI settings? If user clicks YES, prune based on GUI settings. If user clicks NO, do not prune based on GUI settings and disable pruning.

This confirmation can be triggered if pruning is enabled in GUI settings and not found in `bitcoin.conf` during splash screen.

**Comment by prayank23** [comment]
It works fine if I comment this line and launch `bitcoin-qt`

https://github.com/bitcoin-core/gui/blob/6bc51af5c2f29882055dbbb917bbc42ab313164a/src/init.cpp#L1830

**Comment by rebroad** [comment]
> It works fine if I comment this line and launch `bitcoin-qt`
> 
> https://github.com/bitcoin-core/gui/blob/6bc51af5c2f29882055dbbb917bbc42ab313164a/src/init.cpp#L1830

so, a one-line fix?

**Comment by prayank23** [comment]
> so, a one-line fix?

I am not sure why this line exists and if removing this will break something else.

**Comment by Rspigler** [comment]
> I launched bitcoin-qt assuming it will not prune anything because there is nothing mentioned in bitcoin.conf

It should not prune if you set `prune=0` in the config file.  But having nothing in the config file is not the same as stating `Do Not Prune`.  Configuration file should override GUI settings

**Comment by prayank23** [comment]
> It should not prune if you set prune=0 in the config file.

Interesting. I think I will close this issue for now but this problem can needs a better solution because if a software is deleting such important data for

**Comment by hebasto** [comment]
> Configuration file should override GUI settings

More info: [`doc/bitcoin-conf.md`](https://github.com/bitcoin/bitcoin/blob/master/doc/bitcoin-conf.md)

**Comment by Alex20129** [comment]
> It should not prune if you set `prune=0` in the config file. But having nothing in the config file is not the same as stating `Do Not Prune`. Configuration file should override GUI settings

Having nothing in the config file is the same as having "prune=[defaultValue]". I assume, "defaultValue" = "0" in this case, because we talking about days of waiting and hundreds of gigabytes of data, which was downloaded for reasons.
