### ISSUE TITLE
GUI hangs (no windows) when bitcoin-qt runs on macOS Big Sur, and it was compiled with depends (Qt 5.12) 

### ISSUE THREAD

**Issue by hebasto** [bitcoin-core/gui#249]
On macOS Big Sur 11.2.3 (20D91):
```
% xcrun --show-sdk-version
11.1
```

When `bitcoin-qt` is compiled with depends, no window is shown.

That was not the case before [bumping](https://github.com/bitcoin/bitcoin/pull/21376) Qt version to 5.12.10. See https://github.com/bitcoin/bitcoin/pull/21376#issuecomment-795379418

I scratched it a bit. Looks like a problem with the Cocoa integration plugin as dereferencing of the `QGuiApplicationPrivate::platformIntegration()` pointer causes the `EXC_BAD_ACCESS` error.

Probably, it's an upstream bug.

---

UPDATE:

### Case A (SDK 11.1)

- system: Big Sur 11.2.3 (20D91)
```
% xcode-select --print-path    
/Library/Developer/CommandLineTools
% xcrun --show-sdk-path
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
% xcrun --show-sdk-version         
11.1
% make C depends
% CONFIG_SITE=$PWD/depends/x86_64-apple-darwin20.3.0/share/config.site ./configure
% make
% src/qt/bitcoin-qt -regtest -printtoconsole
```
The client runs but the GUI hangs -- no window is created.

### Case B (SDK 11.1 compiled on Catalina, tested on Big Sur)

- build system: Catalina 10.15.7 (19H524) + Xcode 12.4 (12D4e)
```
% xcodebuild -version
Xcode 12.4
Build version 12D4e
% xcode-select --print-path
/Applications/Xcode.app/Contents/Developer
% xcrun --sdk macosx --show-sdk-path
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk
% xcrun --sdk macosx --show-sdk-version
11.1
% make C depends
% CONFIG_SITE=$PWD/depends/x86_64-apple-darwin19.6.0/share/config.site ./configure
% make
% src/qt/bitcoin-qt -regtest -printtoconsole
````
Everything works just fine.

- test system: Big Sur 11.2.3 (20D91)

The binary compiled on Catalina has been moved to Big Sur.
```
% ~/Downloads/bitcoin-qt -regtest -printtoconsole
```
The client runs but the GUI hangs -- no window is created (the same behavior as in the case A).

### Case C (SDK 10.15.6 from downloaded Xcode 11.7)

- system: Big Sur 11.2.3 (20D91)
```
% sudo xcode-select --switch ~/Downloads/Xcode_11.7/Xcode.app
% xcode-select --print-path
/Users/hebasto1/Downloads/Xcode_11.7/Xcode.app/Contents/Developer
% xcrun --show-sdk-path
/Users/hebasto1/Downloads/Xcode_11.7/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk
% xcrun --show-sdk-version         
10.15.6
% make C depends
% CONFIG_SITE=$PWD/depends/x86_64-apple-darwin20.3.0/share/config.site ./configure
% make
% src/qt/bitcoin-qt -regtest -printtoconsole
```
The client runs but the GUI hangs -- no window is created (the same behavior as in the case A).

--- 

Xcode 10.3 and older (SDK 10.14.6) does ~not~ work on Big Sur at all. (see https://developer.apple.com/documentation/macos-release-notes/macos-big-sur-11_0_1-release-notes)

But building depends fail:

### Case D (SDK 10.14.6 from downloaded Xcode 10.3)

- build system: Big Sur 11.2.3 (20D91) + Xcode 10.3 (10G8)
```
% xcodebuild -version
Xcode 10.3
Build version 10G8
% xcode-select --print-path
/Applications/Xcode.app/Contents/Developer
% xcrun --show-sdk-path
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk
% xcrun --show-sdk-version
10.14
% make -C depends native_ds_store
````

The last command fails (looks like an infinite loop).

**Comment by hebasto** [comment]
@fanquake 

FWIW, the build on your `qt_5_15_2_rebased` branch fails as well, unfortunately.

**Comment by hebasto** [comment]
Qt 5.12 [docs](https://doc-snapshots.qt.io/qt5-5.12/macos.html) define supported build environment as Xcode 10 (10.14 SDK).

My attempts to use downloaded Xcode 10.13 on Big Sur failed.

**Comment by jarolrod** [comment]
Confirming this issue on macOS Big Sur 11.2.2 and SDK 11.1, I get a bunch of warnings similar to this (if helpful)

```
ld: warning: direct access in function 'QMetaTypeIdQObject<QWindow*, 8>::qt_metatype_id()' from file '/Users/xyz/Code/Bitcoin/test-depends/bitcoin/depends/x86_64-apple-darwin20.3.0/plugins/platforms/libqcocoa.a(qcocoaintegration.o)' to global weak symbol 'QMetaTypeIdQObject<QWindow*, 8>::qt_metatype_id()::metatype_id' from file 'qt/libbitcoinqt.a(libbitcoinqt_a-walletcontroller.o)' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
```

**Comment by jarolrod** [comment]
Same issue on macOS Catalina 10.15.7 and SDK 10.15.6

**Comment by hebasto** [comment]
@jarolrod 
What is the first dozen of strings in the `debug.log` (about graphics system)?

**Comment by jarolrod** [comment]
Currently on VM. Do you want me to make a partition on my MacBook and try it bare metal?

```
2021-03-17T18:06:48Z Bitcoin Core version v21.99.0-5ef16038a1a8 (release build)
2021-03-17T18:06:48Z Qt 5.12.10 (static), plugin=cocoa (static)
2021-03-17T18:06:48Z Static plugins:
2021-03-17T18:06:48Z  QCocoaIntegrationPlugin, version 330752
2021-03-17T18:06:48Z  QMacStylePlugin, version 330752
2021-03-17T18:06:48Z Style: macintosh / QMacStyle
2021-03-17T18:06:48Z System: macOS 10.15, x86_64-little_endian-lp64
2021-03-17T18:06:48Z Screen: Display 2560x1080, pixel ratio=1.0
```

**Comment by hebasto** [comment]
> Currently on VM.

This could be a reason for `Unable to create basic Accelerated OpenGL renderer.`

**Comment by jarolrod** [comment]
@hebasto was able to build and run on bare metal macOS Catalina 10.15.7 without the `openGL` error. So the `10.15` SDK could be a potential candidate, so is the `10.14` SDK.

I grabbed my `CommandLineTools` directory from my 10.15.7 installation moved it over to my 11.2 installation and changed the SDK with `sudo xcode-select --switch <new-sdk-path>`. On my 10.15.7 machine this directory includes `xcrun` and when you run `xcrun --show-sdk-version` prints `10.15`. But upon moving to the 11.2 machine and switching the SDK, macOS seems to alter some files in this SDK and `xcrun --show-sdk-version` prints `11.1`. So how could I attempt a build on Big Sur using the Catalina SDK?

@fanquake maybe you know how to do this properly?

**Comment by hebasto** [comment]
I updated the OP and the title.

**Comment by hebasto** [comment]
`bitcoin-qt -choosedatadir` results in:

![Screenshot from 2021-03-21 20-14-11](https://user-images.githubusercontent.com/32963518/111916125-1ead7d80-8a82-11eb-9dbb-1db0e8545567.png)

**Comment by hebasto** [comment]
Currently, I have no detailed explanation for that, but the following command fixes the issue:
```
$ export QT_MAC_WANTS_LAYER=1
```

**Comment by hebasto** [comment]
Fixed in https://github.com/bitcoin/bitcoin/pull/21495
