### ISSUE TITLE
bitcoin-0.21.0-win64-setup installer blocked by UAC, Digital Signature certificate revoked.

### ISSUE THREAD

**Issue by user7228** [bitcoin-core/gui#252]
The latest versions (0.21.0 to 0.19.1 tested) of the installers are all blocked by Windows UAC:

![bitcoincore1](https://user-images.githubusercontent.com/69195019/111738706-caa56c00-88bc-11eb-9243-cc3da0a3dd26.png)

The installer's certificates seems revoked:

![bitcoincore2](https://user-images.githubusercontent.com/69195019/111739041-55866680-88bd-11eb-856c-72cc7fc547f2.png)

The above steps are performed with an user account which is a member of Administrators.

**Comment by MarcoFalke** [comment]
cc @achow101 @jonasschnelli

**Comment by fanquake** [comment]
From [IRC](http://www.erisian.com.au/bitcoin-core-dev/log-2021-03-18.html#l-333):
> 2021-03-18T19:21:15  achow101 Note that the windows signing certificate expires next week. I'm in the process of renewing it currently, but it's a process that takes some time

**Comment by achow101** [comment]
For some reason, it appears that when I went to renew the certificate, Comodo decided that the appropriate course of action was to revoke the current one (it expires next week). I'll contact their support tomorrow to see if they can un-revoke it, but I suspect that won't be possible.

My understanding of the windows code signing was that it is timestamped as well, so Windows should've seen that it was signed prior to the revocation date and not given this error. But I guess that understanding is incorrect.

In the meantime, we could direct users to use the unsigned binary?

**Comment by Bosch-0** [comment]
Also experiencing this issue

**Comment by achow101** [comment]
This issue affects 0.21.0, 0.20.0, 0.20.1, and 0.19.2 as they all use the same code signing key.

For those versions, the warning looks like (same as the one in the OP):
![image](https://user-images.githubusercontent.com/3782274/112536557-055b4880-8d84-11eb-8c85-5d40aebf92ab.png)

For comparison, a valid code signed version looks like:
![image](https://user-images.githubusercontent.com/3782274/112536632-1a37dc00-8d84-11eb-845c-3ee42a7f1900.png)

Clicking "Yes" runs the installer.

If we choose to upload a non-code signed version, users will see:
![image](https://user-images.githubusercontent.com/3782274/112536813-4c493e00-8d84-11eb-9b35-628edddceb56.png)

Clicking "More info" shows:
![image](https://user-images.githubusercontent.com/3782274/112536870-608d3b00-8d84-11eb-8979-80a7752c4946.png)

Clicking "Run anyway" shows:
![image](https://user-images.githubusercontent.com/3782274/112536936-76026500-8d84-11eb-8b6c-62a3b6804ed0.png)

Then clicking "Yes" runs the installer in the same way the valid code signed one does.

This is obviously a very scary warning so we should continue to code sign future releases, but for now, the non code signed installer at least allows people to install.

**Comment by jonasschnelli** [comment]
Why did they revoke the current, already payed for, code signing certificate. Even once it expires, existing signatures should still be valid.

It might be that the signing association we founded does no longer check all boxes in their rollout process.

Since - usually pretty restrictive - Apple has not the slightest issue with our signing setup and would only under extreme circumstances revoke a signing certificate, I question the CA (comodo) we are using.

Maybe it is time to reevaluate. Costs should not matter much.

**Comment by laanwj** [comment]
I have for https://bitcoincore.org/bin/bitcoin-core-0.21.0/ and https://bitcoincore.org/bin/bitcoin-core-0.20.1/ moved the -setup.exe to an "archived" directory, uploaded the setup-unsigned.exe instead, also created and signed a new SHA256SUMS.asc with the alternative exe in it.

This should make it at least possible to install while we resolve the signing key issues.

**Comment by hebasto** [comment]
Closing.

See https://github.com/bitcoin/bitcoin/pull/22017.
