### ISSUE TITLE
Tray Icons for applications

### ISSUE THREAD

**Issue by Willtech** [bitcoin-core/gui#253]
Fedora 28 x64
Bitcoin Core v0.21.0

The GUI no longer allows to clear hide tray icon or set minimize to tray. Are anteaters so consumed with the length of their nostrils that they forget the reason we have a tray icon for TSR programs?

Enable;
 - Hide tray icon
 - Minimize to tray

Any report, issue or feature request related to the GUI should be reported at
✅ https://github.com/bitcoin-core/gui/issues/

**Comment by hebasto** [comment]
@Willtech 

The tray icon is available only for desktop environments that support it.
More details:
- https://github.com/bitcoin/bitcoin/pull/14228
- https://doc.qt.io/qt-5/qsystemtrayicon.html#isSystemTrayAvailable

**Comment by Willtech** [comment]
Like this on Fedora 31 with Bitcoin Core v0.20.1
![image](https://user-images.githubusercontent.com/1173622/111944441-c03cd980-8b2b-11eb-8721-2597787adfa1.png)

**Comment by hebasto** [comment]
@Willtech 
> Like this on Fedora 31...

Which desktop environment is used?

> There is no need to pull out functionality that works.

If a desktop functionality is not available for Qt ([`QSystemTrayIcon::isSystemTrayAvailable`](https://doc.qt.io/qt-5/qsystemtrayicon.html#isSystemTrayAvailable)), how it could work?

**Comment by MarcoFalke** [comment]
Fedora 31 is EOL

<!-- https://fedorapeople.org/groups/schedule/f-33/f-33-key-tasks.html

**Comment by Willtech** [comment]
Fedora 33 is EOL at the rate of versioning in Firefox to keep up. The f31 repo still exists. It was better stable and only updated when a feature cond not fit within the existing version instead of Ubuntu style dating bi-annually.

Using Gnome with TopIcons Plus from extensions.gnome.org it works and now I see what has happened, I installed the same extension from fedoraproject.org and it does not actually show the tray.
