### ISSUE TITLE
Show fees in satoshi per byte for incoming and outgoing tx

### ISSUE THREAD

**Issue by viaj3ro** [bitcoin-core/gui#255]
when I double click a transaction in the GUI it only shows the total fees paid for outgoing and no info whatsoever for incoming tx.

It would be very useful if fees were shown in sats/vbyte (or s/vkb) for both, incoming and outgoing tx.

**Comment by jonatack** [comment]
Related issue: https://github.com/bitcoin-core/gui/issues/64

**Comment by hebasto** [comment]
Let's keep discussion in #64.
