### ISSUE TITLE
GUI: Data set on unsupported clipboard mode. QMimeData object will be deleted.

### ISSUE THREAD

**Issue by streamofstars** [bitcoin-core/gui#258]
Right-mouse-button clicking on any transaction in Transactions tab and copying address, label, and so on, results in the following message in the debug.log:

`GUI: Data set on unsupported clipboard mode. QMimeData object will be deleted.`

The copied content is actually getting copied to the clipboard, so no problem with the feature itself, just with the log getting filled with unnecessary messages. I don't know if the issue was present in previous versions or if it's system specific, just noticed that today when I was observing debug.log live when submitting a new transaction.

Bitcoin Core v0.21.0
MacOS 11.2.3

**Comment by hebasto** [comment]
Also see https://github.com/bitcoin/bitcoin/pull/7628#issuecomment-191625574

**Comment by hebasto** [comment]
@streamofstars 

Do you mind testing #277?
