### ISSUE TITLE
Ugly RPC Console Output on macOS

### ISSUE THREAD

**Issue by jarolrod** [bitcoin-core/gui#273]
**Edit**: This is a macOS specific issue. A monospace font is used on Linux and windows, but not on macOS. Add to the list of reasons to embed a regular monospace font.

The help output for any RPC command is formatted differently in the macOS GUI `console` versus a Linux GUI `console`.

With the Linux GUI `console`, the `type/descriptions` for an `argument/result` are shown at a uniform distance from the `argument/result` itself, thanks to the use of a monospace font.

With the macOS GUI `console`, the `type/descriptions` do not line up because a monospace font is not used. This leads to 'ugly' output.

Example: `help setwalletflag`

**macOS GUI RPC Console**
![Screen Shot 2021-04-06 at 7 07 06 PM](https://user-images.githubusercontent.com/23396902/113788966-36386780-970c-11eb-81a5-e9e210cf1a23.png)

**Linux GUI RPC Console**
![Screen Shot 2021-04-08 at 11 49 15 AM](https://user-images.githubusercontent.com/23396902/114057420-8a546080-9860-11eb-9051-9dc8dabcfa2f.png)

**Comment by hebasto** [comment]
> A monospace font is used on Linux and windows, but not on macOS.

Actually, the font family in the default stylesheet https://github.com/bitcoin-core/gui/blob/f0fa32450ec35056b3e1025262aeaef4a24c35ee/src/qt/rpcconsole.cpp#L805-L817
is set correctly to `.AppleSystemUIFontMonospaced`.

But this approach (using styleesheets) does [not work](https://github.com/bitcoin-core/gui/pull/79/commits/22e0114d055b0ac6cdc47af2968b5dc742ba055a) on macOS. Probably, the reason of such behavior is the fact that `.AppleSystemUIFontMonospaced` is a [private](https://doc.qt.io/qt-5/qfontdatabase.html#isPrivateFamily) font family.

**Comment by hebasto** [comment]
Maybe, the following patch
```diff
diff --git a/src/qt/rpcconsole.cpp b/src/qt/rpcconsole.cpp
index 34d055e5a..1acfaa3b2 100644
--- a/src/qt/rpcconsole.cpp
+++ b/src/qt/rpcconsole.cpp
@@ -803,7 +803,7 @@ void RPCConsole::clear(bool clearHistory)
     }
 
     // Set default style sheet
-    QFontInfo fixedFontInfo(GUIUtil::fixedPitchFont());
+    QFontInfo fixedFontInfo(GUIUtil::fixedPitchFont(true));
     ui->messagesWidget->document()->setDefaultStyleSheet(
         QString(
                 "table { }"
```
is a step to fix this issue?

**Comment by hebasto** [comment]
Closing via #477.
