### ISSUE TITLE
Remove unecessary progress bar

### ISSUE THREAD

**Issue by Bosch-0** [bitcoin-core/gui#279]
A progress bar (shown below) is shown when opening the node sync info overlay. It is not necessary to have this and the bottom sync bar - just adds visual clutter. The sync bars are also styled completely different which doesn't look consistent.

![Frame 3](https://user-images.githubusercontent.com/55287964/114367445-06c3a800-9baf-11eb-8958-6ad59c331b35.png)

Tested on Windows 10

**Comment by brunoerg** [comment]
Tested it on MacOS 11.1 and seems unnecessary..
