### ISSUE TITLE
bitcoin-qt 20. GUI opens empty

### ISSUE THREAD

**Issue by NinjaTurtle007** [bitcoin-core/gui#28]
<img>https://imgur.com/AmRCLyZ</img>
After updating from 18. the GUI of bitcoin-qt opens up like this:

The same with version 19.
Version 18. still opens fine by the way
    This is on Ubuntu 19.10, Gnome 3.34.2

-resetguisettings doesn't help

**Comment by hebasto** [comment]
Will try to reproduce.

**Comment by hebasto** [comment]
Ubuntu Eoan 19.10, minimal installation, full update, Bitcoin Core 0.20.0 binary from bitcoincore.org:

![Ubuntu Eoan 19 10_06_07_2020_20_59_32](https://user-images.githubusercontent.com/32963518/86624467-0537d480-bfcc-11ea-9005-cdd47f155ddf.png)

**Comment by hebasto** [comment]
@NinjaTurtle007 
To dissect this issue also log file could be helpful.

---

Also could you create a temporary data directory, say "/home/${USERNAME}/tempdatadir", and run:
```
$ bitcoin-qt -datadir=/home/${USERNAME}/tempdatadir
```
?

---

Another suggestion is to run the same Ubuntu version from live-USB/CD on the same hardware, download and launch `bitcoin-qt` in that environment.

**Comment by hebasto** [comment]
@NinjaTurtle007 

Mind testing the latest [v0.20.1](https://bitcoincore.org/bin/bitcoin-core-0.20.1/bitcoin-0.20.1-x86_64-linux-gnu.tar.gz)?

**Comment by NinjaTurtle007** [comment]
No luck with 0.20.1 either, here is the relevant GUI part from debug.log in the new data dir

> 2020-08-10T17:01:25Z Bitcoin Core version v0.20.1 (release build)
2020-08-10T17:01:25Z Qt 5.9.8 (static), plugin=xcb (static)
2020-08-10T17:01:25Z System: Pop!_OS 20.04 LTS, x86_64-little_endian-lp64
2020-08-10T17:01:25Z Screen: DP-1.3 4x1, pixel ratio=1355.0
2020-08-10T17:01:25Z Screen: DP-1.1 3440x1440, pixel ratio=1.0
2020-08-10T17:01:25Z Screen: eDP-1-1 1920x1080, pixel ratio=1.0
2020-08-10T17:01:25Z GUI: QPainter::begin: Paint device returned engine == 0, type: 2
2020-08-10T17:01:25Z GUI: QPainter::setPen: Painter not active
2020-08-10T17:01:25Z GUI: QPainter::setFont: Painter not active
2020-08-10T17:01:25Z GUI: QPainter::fontMetrics: Painter not active
2020-08-10T17:01:45Z GUI: QPainter::setFont: Painter not active
2020-08-10T17:01:45Z GUI: QPainter::fontMetrics: Painter not active
2020-08-10T17:01:45Z GUI: QPainter::setFont: Painter not active
2020-08-10T17:01:45Z GUI: QPainter::fontMetrics: Painter not active
2020-08-10T17:01:45Z GUI: QPainter::setFont: Painter not active
2020-08-10T17:01:45Z GUI: QPainter::end: Painter not active, aborted
2020-08-10T17:01:52Z Assuming ancestors of block 0000000000000000000f2adce67e49b0b6bdeb9de8b7c3d7e93b21e7fc1e819d have valid signatures.

**Comment by hebasto** [comment]
This part
> 2020-08-10T17:01:25Z Screen: DP-1.3 4x1, pixel ratio=1355.0

looks very strange for me...

**Comment by NinjaTurtle007** [comment]
Indeed, this is infact  5120x1440 super ultrawide monitor which has the same scaling like the others. No idea why it shows it like that in the log.

**Comment by hebasto** [comment]
What are outputs of `xdpyinfo | grep -B 2 resolution` and `xrandr`?

**Comment by NinjaTurtle007** [comment]
>  xdpyinfo | grep -B 2 resolution
screen #0:
  dimensions:    7040x2880 pixels (1863x762 millimeters)
  resolution:    96x96 dots per inch





> xrandr
Screen 0: minimum 8 x 8, current 7040 x 2880, maximum 32767 x 32767
DP-1.1 connected 3440x1440+956+0 (normal left inverted right x axis y axis) 800mm x 335mm
   3440x1440     59.97*+  49.99    29.99  
   2560x1080     60.00    59.94    50.00  
   1920x1080     60.00    59.94    50.00  
   1680x1050     59.95  
   1600x900      60.00  
   1280x1024     60.02  
   1280x800      59.81  
   1280x720      60.00    59.94    50.00  
   1152x864      60.00  
   1024x768      60.00  
   800x600       60.32  
   720x576       50.00  
   720x480       59.94  
   640x480       59.94    59.93  
DP-1.3 connected primary 5120x1440+0+1440 (normal left inverted right x axis y axis) 1mm x 1mm
   3840x1080    119.97 +  99.96    59.97  
   5120x1440    119.97   100.00    59.98* 
   2560x1440     59.95  
   2560x1080    119.88   100.00    60.00    59.94  
   1920x1080    119.88   100.00    60.00    59.94  
   1680x1050     59.95  
   1600x900      60.00  
   1440x900      59.89  
   1280x1024     75.02    60.02  
   1280x800      59.81  
   1280x720      60.00  
   1152x864      75.00  
   1024x768      75.03    70.07    60.00  
   800x600       75.00    72.19    60.32    56.25  
   640x480       75.00    72.81    59.94  
DP-0 disconnected (normal left inverted right x axis y axis)
DP-1 disconnected (normal left inverted right x axis y axis)
HDMI-0 disconnected (normal left inverted right x axis y axis)
eDP-1-1 connected 1920x1080+5120+1440 (normal left inverted right x axis y axis) 344mm x 193mm
   3840x2160     60.00 +  59.98    59.97  
   3200x1800     59.96    59.94  
   2880x1620     59.96    59.97  
   2560x1600     59.99    59.97  
   2560x1440     59.99    59.99    59.96    59.95  
   2048x1536     60.00  
   1920x1440     60.00  
   1856x1392     60.01  
   1792x1344     60.01  
   2048x1152     59.99    59.98    59.90    59.91  
   1920x1200     59.88    59.95  
   1920x1080     60.01    59.97    59.96    59.93* 
   1600x1200     60.00  
   1680x1050     59.95    59.88  
   1600x1024     60.17  
   1400x1050     59.98  
   1600x900      59.99    59.94    59.95    59.82  
   1280x1024     60.02  
   1440x900      59.89  
   1400x900      59.96    59.88  
   1280x960      60.00  
   1440x810      60.00    59.97  
   1368x768      59.88    59.85  
   1360x768      59.80    59.96  
   1280x800      59.99    59.97    59.81    59.91  
   1152x864      60.00  
   1280x720      60.00    59.99    59.86    59.74  
   1024x768      60.04    60.00  
   960x720       60.00  
   928x696       60.05  
   896x672       60.01  
   1024x576      59.95    59.96    59.90    59.82  
   960x600       59.93    60.00  
   960x540       59.96    59.99    59.63    59.82  
   800x600       60.00    60.32    56.25  
   840x525       60.01    59.88  
   864x486       59.92    59.57  
   800x512       60.17  
   700x525       59.98  
   800x450       59.95    59.82  
   640x512       60.02  
   720x450       59.89  
   700x450       59.96    59.88  
   640x480       60.00    59.94  
   720x405       59.51    58.99  
   684x384       59.88    59.85  
   680x384       59.80    59.96  
   640x400       59.88    59.98  
   576x432       60.06  
   640x360       59.86    59.83    59.84    59.32  
   512x384       60.00  
   512x288       60.00    59.92  
   480x270       59.63    59.82  
   400x300       60.32    56.34  
   432x243       59.92    59.57  
   320x240       60.05  
   360x202       59.51    59.13  
   320x180       59.84    59.32  
  2560x1440 (0x1dc) 241.500MHz +HSync -VSync
        h: width  2560 start 2608 end 2640 total 2720 skew    0 clock  88.79KHz
        v: height 1440 start 1443 end 1448 total 1481           clock  59.95Hz
  1680x1050 (0x1c7) 146.250MHz -HSync +VSync
        h: width  1680 start 1784 end 1960 total 2240 skew    0 clock  65.29KHz
        v: height 1050 start 1053 end 1059 total 1089           clock  59.95Hz
  1280x1024 (0x1c9) 108.000MHz +HSync +VSync
        h: width  1280 start 1328 end 1440 total 1688 skew    0 clock  63.98KHz
        v: height 1024 start 1025 end 1028 total 1066           clock  60.02Hz
  1440x900 (0x1e2) 106.500MHz -HSync +VSync
        h: width  1440 start 1520 end 1672 total 1904 skew    0 clock  55.93KHz
        v: height  900 start  903 end  909 total  934           clock  59.89Hz
  1280x800 (0x1ca) 83.500MHz -HSync +VSync
        h: width  1280 start 1352 end 1480 total 1680 skew    0 clock  49.70KHz
        v: height  800 start  803 end  809 total  831           clock  59.81Hz
  1152x864 (0x1ce) 81.620MHz -HSync +VSync
        h: width  1152 start 1216 end 1336 total 1520 skew    0 clock  53.70KHz
        v: height  864 start  865 end  868 total  895           clock  60.00Hz
  1024x768 (0x1cf) 65.000MHz -HSync -VSync
        h: width  1024 start 1048 end 1184 total 1344 skew    0 clock  48.36KHz
        v: height  768 start  771 end  777 total  806           clock  60.00Hz
  800x600 (0x1d0) 40.000MHz +HSync +VSync
        h: width   800 start  840 end  968 total 1056 skew    0 clock  37.88KHz
        v: height  600 start  601 end  605 total  628           clock  60.32Hz
  800x600 (0x1e9) 36.000MHz +HSync +VSync
        h: width   800 start  824 end  896 total 1024 skew    0 clock  35.16KHz
        v: height  600 start  601 end  603 total  625           clock  56.25Hz
  640x480 (0x1d3) 25.175MHz -HSync -VSync
        h: width   640 start  656 end  752 total  800 skew    0 clock  31.47KHz
        v: height  480 start  490 end  492 total  525           clock  59.94Hz

**Comment by hebasto** [comment]
> Indeed, this is infact 5120x1440 super ultrawide monitor which has the same scaling like the others (100% so no scaling actually). No idea why it shows it like that in the log.

Could you try to disconnect this device, reboot OS, and test `bitcoin-qt`?

**Comment by hebasto** [comment]
FWIW, tested latest v0.20.1 on just installed Pop!_OS 20.04 LTS. It works flawlessly for me :)

**Comment by NinjaTurtle007** [comment]
Yup, works perfect without that monitor even without restart.  Thanks for narrowing it down to the monitor, great work! :)
Now if I can only make it work with that montior as well, since it's my main one would be awesome!

**Comment by hebasto** [comment]
> btw, bitcoin 0.18 still works perfect on that same setup.

Not sure if it is the reason, but 0.18 uses Qt 5.9.7, and 0.19+ uses Qt 5.9.8. Have you done OS upgrade?

Couldn't say more being not able to reproduce the issue locally :)

btw, you could try to overwrite EDID info for your monitor

**Comment by NinjaTurtle007** [comment]
I did upgrade the OS but just today, from 19.10 to 20.04 and it was the same issue on 19.10 as well.

How do I overwrite EDID and could that mess up my current multi-monitor setup? Took a while to make it work via a dock :)

**Comment by shaun-ba** [comment]
Also having this issue on a Samsung superwide monitor and 20.04, bitcoin-qt runs and syncs watching debug logs but no GUI at all, I can't do anything therefore.
