### ISSUE TITLE
Refactored GUI mockup

### ISSUE THREAD

**Issue by dillonjohnbrown** [bitcoin-core/gui#285]
For this mockup I wanted to use space more efficiently and use more standard OS elements. Is something like this worth investing more of my time into? The gist of what I'm aiming for is here, but it needs more work.

All feedback is welcome. 
![Artboard](https://user-images.githubusercontent.com/49077521/115159685-4116c480-a049-11eb-8452-d20f4fb0d4ec.png)

**Comment by promag** [comment]
Personally I don't like the layout.

What Is "Use previous address"?

**Comment by dillonjohnbrown** [comment]
Can you be more specific about what you don't like?

> What Is "Use previous address"?

It's this button on the Send tab.
<img width="42" alt="Screen Shot 2021-04-18 at 1 42 00 PM" src="https://user-images.githubusercontent.com/49077521/115160206-dfa42500-a04b-11eb-868d-197753f5c026.png">

**Comment by promag** [comment]
I prefer each view separated. I get the point of this layout, but I don’t think it’s the correct approach here. Having this as an option would add extra reviewing effort which I don’t think is also desirable.

**Comment by Bosch-0** [comment]
> I prefer each view separated. 

Agree, this page looks too busy. I would keep send/recieve on their own page and re-structure the overview page to be cleaner

**Comment by jarolrod** [comment]
@dillonjohnbrown have you joined the bitcoin design community? https://bitcoin.design/guide/
You can present any designs to the #bitcoin-core-gui slack channel, a couple of designers on there who will review with you.

**Comment by hebasto** [comment]
I'd suggest to move this and any similar discussion to https://github.com/bitcoin-core/gui-qml.
