### ISSUE TITLE
Remove indented/raised borders elements on Windows

### ISSUE THREAD

**Issue by Bosch-0** [bitcoin-core/gui#303]
Somewhere between the last GUI update and current master 4cfe6c37d956be58e6228f50833d25b84aafe55a the Windows version of the GUI has these indented / raised border designs applied to them which has resulted in a very visually cluttered GUI. I think this style is only visually bad on Windows as other recent screenshots of master from macOS / Linux don't seem to be effected.  Below is an example from the overview section:

![Group 265](https://user-images.githubusercontent.com/55287964/116487199-fb1bf500-a8c1-11eb-996c-417f355c15aa.png)

It has also made the sections more condensed as I assume each widget has a size constraint and these borders are taking up extra space. It would be much more visually appealing to have this reverted back to the old style (like in the before above).

**Comment by RandyMcMillan** [comment]
Is it possible that these "flat" properties being removed is the cause?

https://github.com/bitcoin-core/gui/commit/67c59ae4793b1a5ebe0c4c542abf3c095e6a658b#diff-bf3f2d3ef0cdd76cd0ee7ed2bfbdea67f03c24a4b85fcfde206acc291e31b4af

**Comment by jarolrod** [comment]
That is an issue with your local qt installation, you have an old version of qt building the GUI.

**Comment by jarolrod** [comment]
@RandyMcMillan that has nothing to do with this issue. That removed a flat property on a button

**Comment by Bosch-0** [comment]
Mmh not sure how it would be doing that I haven't configured anything - I'll re-build.

**Comment by jarolrod** [comment]
@Bosch-0  can you take a Screenshot of the `About Qt` window

**Comment by Bosch-0** [comment]
Seems its the latest version? 

![image](https://user-images.githubusercontent.com/55287964/116502882-4d234180-a8e7-11eb-8187-12377685b19a.png)

**Comment by Bosch-0** [comment]
Seems other using windows are also experiencing this when building - https://github.com/bitcoin-core/gui/pull/300

**Comment by hebasto** [comment]
Confirming. Could this be a difference between Qt 5.9.8 and Qt 5.12.10 (https://github.com/bitcoin/bitcoin/pull/21376)?

**Comment by hebasto** [comment]
@Bosch-0 

Do you mind testing #322?

**Comment by hebasto** [comment]
@Bosch-0 

The right solution is https://github.com/bitcoin/bitcoin/pull/22133. Thanks to @jarolrod!

**Comment by Bosch-0** [comment]
Will test that asap, ty @jarolrod
