### ISSUE TITLE
Unable to sign PSBT loaded from file/clipboard on the second time, getting "could not sign any more inputs" error

### ISSUE THREAD

**Issue by beeant** [bitcoin-core/gui#312]
So I have bitcoin-core wallet.

1. I imported one of the receiving addresses from bitcoin-core to electrum as a watch only wallet.
2. I created a raw transaction using electrum
3. In electrum, I exported the raw transaction as a file (psbt file)
4. Load the PSBT file using bitcoin-core
5. Successfully signed the transaction on bitcoin-core

I repeated the process for the second time and I am getting this error, "could not sign any more inputs"

I searched the error message, it seems be here:
https://github.com/bitcoin/bitcoin/blob/7fcf53f7b4524572d1d0c9a5fdc388e87eb02416/src/qt/psbtoperationsdialog.cpp#L81

PS:
before I did the second try, I changed the passphrase.
bitcoin-core is on an offline computer.
bicoin core v0.21.0

I wonder if changing the passpharse on bitcoincore is related to this problem.
As far as I know the passphrase is only used to encrypt the wallet file? It has nothing to do with the private keys and address like mnemonic seeds?

**Comment by beeant** [comment]
After talking to someone on stackexchange, he had the same issue, and finally found that to make it work, we need to do `walletpassphrase` on console before signing it.

Should there be a UI fix or a better error message for this?

**Comment by Bosch-0** [comment]
> As far as I know the passphrase is only used to encrypt the wallet file? It has nothing to do with the private keys and address like mnemonic seeds?

The passphrase is only used to encrypt your locally stored private keys, Bitcoin Core does not have wallet database encryption. We should have a pop-up to enter the private keys passphrase when signing the PSBT.

**Comment by meshcollider** [comment]
This PR will fix this: https://github.com/bitcoin/bitcoin/pull/23106
