### ISSUE TITLE
Bitcoin Core on Ubuntu 18.04 not allowing to chose data directory

### ISSUE THREAD

**Issue by alexstrbonn** [bitcoin-core/gui#32]
When starting Bitcoin Core 0.20.0-x86_64 ( https://bitcoin.org/bin/bitcoin-core-0.20.0/bitcoin-0.20.0-x86_64-linux-gnu.tar.gz) ) on Ubuntu 18.04 there is no option to set a custom data directory in the GUI.

All options in the GUI are greyed out. See image, please.

![image](https://user-images.githubusercontent.com/67925318/87402540-01074a80-c5bc-11ea-9476-bce4c3f08e22.png)

![image](https://user-images.githubusercontent.com/67925318/87402766-4fb4e480-c5bc-11ea-9b93-5a07c6a9b3f5.png)

**Comment by MarcoFalke** [comment]
Similar: https://github.com/bitcoin-core/packaging/issues/46

**Comment by alexstrbonn** [comment]
Thanks. Here Bitcoin Core has NOT been installed via the Snapstore, but manually using the tar.gz file from Bitcoin.org.

**Comment by hebasto** [comment]
I can confirm this bug on Linux Mint 20.

**Comment by alexstrbonn** [comment]
Any known solution to this bug?

**Comment by hebasto** [comment]
> Any known solution to this bug?

See related #33.

**Comment by hebasto** [comment]
Fixed in https://github.com/bitcoin/bitcoin/pull/19536.

@alexanderkjeldaas Mind testing?
