### ISSUE TITLE
bitcoinbuilds.org macOS CI is broken

### ISSUE THREAD

**Issue by Sjors** [bitcoin-core/gui#327]
See e.g. https://github.com/bitcoin-core/gui/pull/325 build log: https://bitcoinbuilds.org/index.php?ansilog=be6bfe20-7e28-4344-9664-6ae1ff46dbb9.log

```
4643   In file included from ./boost/config.hpp:44:
L4644   ./boost/config/detail/select_stdlib_config.hpp:18:12: fatal error: 'cstddef' file not found
L4645   #  include <cstddef>
L4646              ^~~~~~~~~
L4647   1 error generated.
```

cc @jonasschnelli

**Comment by hebasto** [comment]
It should adopt https://github.com/bitcoin/bitcoin/pull/19817 changes.

**Comment by hebasto** [comment]
It is fixed now: https://bitcoinbuilds.org/index.php?job=8eddad05-f339-4d42-820e-57b44d288e85

Closing.

**Comment by jonasschnelli** [comment]
Fixed...(for upcoming builds).

**Comment by hebasto** [comment]
@jonasschnelli 
> Fixed...(for upcoming builds).

Thank you!

[Recent](https://bitcoinbuilds.org/?build=11919) builds are green, so closing.
