### ISSUE TITLE
Should Bitcoin Core quit when something goes wrong?

### ISSUE THREAD

**Issue by GaylordTuring** [bitcoin-core/gui#364]
Bitcoin Core quits without any error message being shown. The application just disappears from the taskbar. I realize that things can go wrong (and I would very much figure out what goes wrong for me specifically), but should the application quit rather than gracefully show an error message and prompt the user to do something (for example check the error log or restart the software)? That is, is this type of behavior a bug or a feature? I definitely think that it shouldn't work this way.

**Expected behavior**

Bitcoin Core should still be open, possibly with some error message showing that it has stopped running with some suggestions what the user can do.

**Actual behavior**

Program quits and disappears from the taskbar.

**To reproduce**

I guess this depends on your system, but for me, I simply import my old wallet into the wallet folder, start Bitcoin Core and then wait. When searching for this error online, I see that it has been an issue more or less from the start.

**System information**

I run version 0.21.1, 64-bit, of Bitcoin Core, downloaded as an installer from Bitcoin.org. I'm using Windows version 10.0.19042.

**Comment by hebasto** [comment]
Could you provide your `debug.log` file?

**Comment by GaylordTuring** [comment]
Sure, here's one from my latest run.

[debug - Copy.log](https://github.com/bitcoin-core/gui/files/6644548/debug.-.Copy.log)

**Comment by hebasto** [comment]
@GaylordTuring 

What is the `Z:` drive? External? USB?

**Comment by GaylordTuring** [comment]
@hebasto It's one of my internal drives (this is a desktop PC). Bitcoin Core itself is installed on my main drive, C:, but I chose to have the chaindata stored on my Z: drive, which is a 2TB spinning hard drive. I've installed numerous games on that drive without any problems, so it seems to be doing fine.

**Comment by hebasto** [comment]
@GaylordTuring 

Could you try to run the `bitcoind.exe`--the Bitcoin Core daemon without the GUI--and to see if it succeeds?

**Comment by GaylordTuring** [comment]
@hebasto First of all, I was able to continue the process of downloading the whole blockchain by deleting all the contents of my chaindata folder. I've done this before, so I'm not sure why it worked this time, but whatever.

However (and this is a great illustration of my general concern), when trying to load my wallet, Bitcoin Core just shuts down. No warning messages, no popups, no nothing. It's just gone. This, again, is a behavior I don't think should manifest itself ever, no matter how many error the application throws under the hood.

I did try to run bitcoind instead. At first, it worked, but after trying to load my wallet via the cli, it just shut down (again, non gracefully; it just disappeared), and the cli gave me an error message saying that the daemon needed to run. Ever since that happening, running bitcoind just results in it closing itself after a while. The last thing I manage to see in the window, which I don't think should close itself, is "Rescan started from block something, something....". No extra log messages are written to either debug.log or db.log.

**Comment by hebasto** [comment]
@GaylordTuring 

> I did try to run bitcoind instead. At first, it worked, but after trying to load my wallet via the cli, it just shut down (again, non gracefully; it just disappeared), and the cli gave me an error message saying that the daemon needed to run. Ever since that happening, running bitcoind just results in it closing itself after a while. The last thing I manage to see in the window, which I don't think should close itself, is "Rescan started from block something, something....". No extra log messages are written to either debug.log or db.log.

Thanks for testing! It seems this issue should be moved into the [main repo](https://github.com/bitcoin/bitcoin/issues) to attract the attention of more developers who works on node (daemon) and wallet stuff.

As the GUI is, essentially, another layer, it just processes errors that are received from the node (daemon) and wallet code.

**Comment by GaylordTuring** [comment]
@hebasto Do you mean that someone should move it or that I should create a new issue in the main repo?

**Comment by hebasto** [comment]
@GaylordTuring 

> @hebasto Do you mean that someone should move it or that I should create a new issue in the main repo?

You could open a new issue in the main repo, describing steps to reproduce it with `bitcoind` and your wallet. Then this issue could be closed.

**Comment by hebasto** [comment]
Moved to https://github.com/bitcoin/bitcoin/issues/22398.
