### ISSUE TITLE
Peer table (node window) does not remain sorted on update

### ISSUE THREAD

**Issue by rebroad** [bitcoin-core/gui#367]
![image](https://user-images.githubusercontent.com/1530283/123112095-5c30f680-d435-11eb-9962-45eaa554ce3a.png)

This issue was introduced somewhere between 672870ab7ba51b1fc40f263a1c71ebcf165b1229 and c8571486364d6e9ca8c86bd1c81e230ca64f8904

**Comment by rebroad** [comment]
c8571486364d6e9ca8c86bd1c81e230ca64f8904 is also good

could not bisect past 310fab49282d507e5fa710afb20d036604bbf3a2 as getting the error:-
> bitcoin-qt: wallet/init.cpp:127: WalletInit::Construct(NodeContext&) const::<lambda()>: Assertion `"node.args" && check' failed.

**Comment by rebroad** [comment]
ecbd91153875c8cdd5b92b840afc116f65e457fb is the first bad commit

**Comment by hebasto** [comment]
Can confirm this issue.

**Comment by jarolrod** [comment]
confirming issue as well
