### ISSUE TITLE
Restore wallet via the GUI

### ISSUE THREAD

**Issue by lsilva01** [bitcoin-core/gui#383]
`bitcoin-qt` has the `Backup Wallet` option (`File` -> `Backup Wallet...`).
But apparently there is no way to restore the wallet from a backup file via the GUI.
The only way to do this is to replace the `wallet.dat` of a newly created wallet with the backup file, which can hardly be considered an intuitive way.

Maybe it would be interesting to add a `Restore Wallet From Backup` option in `bitcoin-qt`.

**Comment by Rspigler** [comment]
This could be a good followup to https://github.com/bitcoin/bitcoin/pull/22541
