### ISSUE TITLE
Add go back button to `Confirm wallet encryption` window, add cancel button to `wallet to be encrypted` window

### ISSUE THREAD

**Issue by jarolrod** [bitcoin-core/gui#394]
When i go to create a wallet, I have the option to encrypt my wallet. If i choose this option, the next step is to choose a password. 
ok 👍, I've chosen a password. Now, I click on the `Ok` button to continue to the next screen which is the following warning:

![warning](https://user-images.githubusercontent.com/23396902/128109376-a892312b-a93b-4cf9-a0fc-24f70d93cd4c.png)

Now i have been reminded with the life changing knowledge that if I lose this passphrase then I lose all of my Bitcoin. I now have to think about whether or not the wallet I have chosen is what i want it to be. If I am still content with my wallet, then I can continue on. If i am not content with my password, I cannot go back and change it. Instead, I have to click the `Cancel` button and start all over. The `Confirm wallet encryption` wallet should introduce a `go back` button that allows me to 'go back' to the `Encrypt Wallet` window. 

Additionally, the `Cancel` button in this window can be removed. If we go back we can cancel in the `Encrypt Wallet` window, if we go forward -> read on ...

If I was content with my wallet password I can continue on. The next window is another message reminding me that wallet is going to be encrypted and that this does not fully protect my Bitcoin from being stolen:

![wallet-to-be-encrypted](https://user-images.githubusercontent.com/23396902/128109928-84dfed23-bd3f-4527-bb68-183bc88fa4b1.png)

If I am content with this security assumption I can continue on, but at this stage there is no option to be able to cancel my creation of this wallet. The `Wallet to be encrypted` window should introduce a `Cancel` button that 'cancels' the creation of this wallet.

**Comment by MarcoFalke** [comment]
See also https://github.com/bitcoin/bitcoin/issues/18085

**Comment by hebasto** [comment]
A bit related https://github.com/bitcoin-core/gui/issues/151.

**Comment by hebasto** [comment]
@jarolrod 

Mind reviewing https://github.com/bitcoin-core/gui/pull/722?
