### ISSUE TITLE
External Signer can be enabled even when external signer script is not set

### ISSUE THREAD

**Issue by jarolrod** [bitcoin-core/gui#395]
The `External Signer` option when creating a wallet is supposed to be disabled while the external signer script has not been set in settings. There is a way to enable this option even though the script has not been set, then if you were to create an External Signer wallet the gui will crash because the external signer script was never set:
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  GetExternalSigner: restart bitcoind with -signer=<cmd>
Aborted (core dumped)
```

**Steps to reproduce:**

No special preparation. Just required that the external signer script has not be set in settings. This is to ensure that proper functionality is that the `External Signer` script option is supposed to be disabled.

1) Go to create a new wallet
2) Notice that the `External Signer` option is disabled, as it is supposed to be
3) Select, then de-select `Encrypt Wallet`
4) The `External Signer` option is now enabled, when it is not supposed to be
5) Select the now enabled `External Signer` option and create wallet
6) GUI will crash

**Comment by Rspigler** [comment]
When you say:

> The `External Signer` option is disabled

do you mean the `External Signer` script path remains empty, or is there some other option I am missing?
