### ISSUE TITLE
Peer address column sorting does not honor the inbound/outbound arrow prefix

### ISSUE THREAD

**Issue by wodry** [bitcoin-core/gui#397]
See this peer address column:
![screenshot](https://user-images.githubusercontent.com/8447873/128592825-0824b19d-4b4e-4f40-9195-018e19d1ef7a.png)

**Expected behavior**
Peer number 196 is sorted below peer number 424, because it is sorted by the first character (arrow) first.

**Actual behavior**
Peer number 196 is sorted below peer number 110. The first (arrow) character seems not to be relevant for sorting?

**To reproduce**
Run with both Onion and I2P network enabled and watch the peer table.

**System information**
22.0rc2
Debian Buster amd_64

**Comment by hebasto** [comment]
@wodry 
Is this sorting order was restored from the previous Bitcoin Core run, or was set manually in the current session?

**Comment by hebasto** [comment]
@wodry 
Does sorting work for you without https://github.com/bitcoin-core/gui/pull/375/commits/986bf78d7e8fd9b69841ecb0decaff840efe9cff?

**Comment by wodry** [comment]
I wanted to sort by peer address (to more easily count inbound/outbound connections), so I clicked manually on the peer address column header (where the little triangle is), to be sure, sorting by address is active. Then I noticed this issue. Clicking more times on the header reverses sorting order as expected, but issue persists.

**Comment by hebasto** [comment]
For now, only address itself in considered during sorting:
https://github.com/bitcoin-core/gui/blob/03826aecc56c5c5c76570805897c2ddf92e11ab6/src/qt/peertablesortproxy.cpp#L27-L28

> I wanted to sort by peer address (to more easily count inbound/outbound connections), so I clicked manually on the peer address column header (where the little triangle is), to be sure, sorting by address is active. Then I noticed this issue. Clicking more times on the header reverses sorting order as expected, but issue persists.

Maybe you could be interested in #317 or #363?

**Comment by wodry** [comment]
> Maybe you could be interested in #317 or #363?

I do not find them reasonable, see my expressions there.

I like the sorting functionality that honors the inbound/outbound arrow prefix. I cannot imagine any use case for not honoring the prefix. Honoring the prefix makes sense, see my use case here in OP.

Was the prefix sorting honoring removed? In the past I did not stumble upon this issue, but not sure if I tested it explicitly.

I would be thankful if someone could create a PR to fix this issue. I will look if I can create one, too, if it should be rather easy.

**Comment by hebasto** [comment]
> I like the sorting functionality that honors the inbound/outbound arrow prefix. I cannot imagine any use case for not honoring the prefix. Honoring the prefix makes sense, see my [use case](https://github.com/bitcoin-core/gui/issues/397#issuecomment-894621607).

> ... to more easily count I2P and Onion inbound/outbound connections

Your use case, actually, requires filtering :)

> Was the prefix sorting honoring removed?

The implementation remains unchanged since it was introduced in https://github.com/bitcoin/bitcoin/pull/4225.

**Comment by wodry** [comment]
This issue would be obsoleted by alternatives like #401 (B.2) or (B.3)

**Comment by hebasto** [comment]
Closing, as #317 has been merged.
