### ISSUE TITLE
GUI disappears

### ISSUE THREAD

**Issue by wallart1** [bitcoin-core/gui#405]
bitcoin-qt starts fine and shows the GUI. After some period, the GUI disappears. There seems to be no way to restart it unless I kill the bitcoin-qt process and restart it. System information is in the attached txt file. TLDR; Linux Mint (20.2) Cinnamon (5.0.5) with kernel 5.11.0-25-generic. I would be happy with a command line option that causes the GUI to restart.

If I have the GUI's Information window showing, it does not disappear. Just the main (wallet) window disappears.

[systeminfo.txt](https://github.com/bitcoin-core/gui/files/7003905/systeminfo.txt)

**Comment by hebasto** [comment]
@wallart1 

Could you provide your `debug.log` file? Are you sure your GUI windows was not minimized?

**Comment by wallart1** [comment]
[debuglog.txt](https://github.com/bitcoin-core/gui/files/7006660/debuglog.txt)
(I edited the log to show just the part since the last startup. The main window is currently missing.)

The node window has an icon in the panel. But there is nothing related to bitcoin-qt in the tray.

Now that you mention it, if I minimize the window, it disappears then, also. So I have developed the habbit of always leaving it open in a different desktop workspace. I have checked all the workspaces, and it's not in any of them, either.

Thanks for you help. :)

**Comment by hebasto** [comment]
> The node window has an icon in the panel. But there is nothing related to bitcoin-qt in the tray.

Nothing like that

![Screenshot from 2021-08-18 20-05-43](https://user-images.githubusercontent.com/32963518/129941530-cccb2149-9363-485e-9a8b-0c75db6fec82.png)

?

**Comment by wallart1** [comment]
![Window Settings](https://user-images.githubusercontent.com/84820338/129945118-47082844-40f0-47d7-8485-8f38f5db6130.png)

I took the -min option out of the startup command, and now things seem to be normal. There is an icon in the tray, and the windows seem to be staying open.

Again, thank you so much for your help.

**Comment by hebasto** [comment]
Closing for now. Could be re-opened if more questions arise.
