### ISSUE TITLE
Slovenian (sl) translation missing in version 22.0 in the OS X build

### ISSUE THREAD

**Issue by mmazi** [bitcoin-core/gui#422]
In Bitcoin Core GUI I don't see the option to choose Slovenian (sl) as the interface language. I had it selected in v 0.21. 

Slovenian is over 98% translated (only some obscure messages are still left untranslated on Transifex -- I myself did a large part of the translation) and I think it should be included.

I find it strange, however, that Slovenian seems to be included in the source code:
https://github.com/bitcoin-core/gui/search?q=sl

(Also please note that Slovenian / slovenščina / sl is a distinct language from Slovakian / slovenčina / sk.)

<img width="561" alt="Screenshot 2021-09-14 at 14 12 21" src="https://user-images.githubusercontent.com/294075/133255485-7c4ec5b4-e78b-45b4-b672-7e40c35d9cbb.png">

**Comment by hebasto** [comment]
@mmazi 

Actually, the most of strings in [Slovenian (sl) translation](https://www.transifex.com/bitcoin/bitcoin/translate/#sl/qt-translation-022x/321669431) on Transifex.com are _not_ translated. They are just English strings.

Therefore, this translation has been skipped.

You could improve the Slovenian (sl) translation for the next release on Transifex.com.

**Comment by mmazi** [comment]
You're right, thanks.

I'll see how this can be fixed. Not sure how this happened. Before this last version, all translations from the previous version just propagated to the next, but this seems to not have happened this time. Perhaps has something to do with the switch to the XLIFF format.

**Comment by hebasto** [comment]
> Perhaps has something to do with the switch to the XLIFF format.

Cannot confirm or deny it. The "Translation Memory" feature on Transifex.com works regardless of source format.

Closing this for now.

**Comment by mmazi** [comment]
Thanks.

Unfortunately, almost all existing Slovenian translations from older versions seem to be missing from Translation Memory too (so they are completely unavailable in 22.x). I wrote about it [on Transifex](https://www.transifex.com/bitcoin/teams/159/discussions/20542/) too.

**Comment by hebasto** [comment]
> Thanks.
> 
> Unfortunately, almost all existing Slovenian translations from older versions seem to be missing from Translation Memory too (so they are completely unavailable in 22.x). I wrote about it [on Transifex](https://www.transifex.com/bitcoin/teams/159/discussions/20542/) too.

The "Suggestions" tab seems could be useful.

**Comment by mmazi** [comment]
Thanks, I guess I'll use Suggestions then.

The process will be prone to error, unfortunately (and also time consuming). Perhaps someone can advise whether exporting from 0.21.x and importing into 22.x would be a good idea?
