### ISSUE TITLE
Weird status icons stacking - ghost icon

### ISSUE THREAD

**Issue by katesalazar** [bitcoin-core/gui#428]
There are at least up to six icons in order:

1. unit: btc, sat...
2. HD: disabled/enabled.
3. wallet lock.
4. proxy (disabled/enabled ?).
5. network status and number of connections.
6. syncing/synced.

I think there's a way to make a ghostly placeholder appear between the unit (btc, sat...) and the proxy "P".

**Expected behavior**

A normal stacking of icons.

**Actual behavior**

Too much spacing between the unit and the proxy "P".

**To reproduce**

Boot Bitcoin Core Qt without a wallet loaded. Just happens, in my case...

**System information**

Self-compiled v22.0 tag.

Contemporary Debian GNU/Linux, KDE 5.54.0, Qt 5.11.3, xcb.

**Other**

I might have some time to bisect this.

**Comment by katesalazar** [comment]
Apparently the synced/unsynced low bar icon tooltip is immediately in sync with the transaction details window, while the transaction tooltip stays "one block late".

**Comment by katesalazar** [comment]
the v0.21.0 tag showing the same as the v22.0 tag

**Comment by katesalazar** [comment]
In the v0.20.0 I'm having a hard time to have it not autoloading or autocreating a wallet on startup, so no more bisecting for now.

**Comment by hebasto** [comment]
@katesalazar 

Screenshots could be very helpful to describe a visual issue :)

FWIW, the relevant code is here: https://github.com/bitcoin-core/gui/blob/d648bbb0a7909aed953b6f7907690134606a033a/src/qt/bitcoingui.cpp#L159-L181

**Comment by katesalazar** [comment]
Alright.

---

<img width="762" alt="Screen Shot 2021-09-29 at 19 51 23" src="https://user-images.githubusercontent.com/52637275/135322838-b622d600-2a28-438d-adac-3f1a10b16260.png">
fig 1. booting without wallet

---

<img width="665" alt="Screen Shot 2021-09-29 at 19 51 33" src="https://user-images.githubusercontent.com/52637275/135322862-82b11ef1-daee-4883-9354-6f98bbcc55a3.png">
fig 2. booted without wallet, working

---

<img width="145" alt="Screen Shot 2021-09-29 at 19 52 11" src="https://user-images.githubusercontent.com/52637275/135322901-e3444a04-7fce-4c10-9de0-ac2ec77e0a67.png">
fig 3. booted without wallet, working (through a proxy)

---

<img width="152" alt="Screen Shot 2021-09-29 at 19 52 37" src="https://user-images.githubusercontent.com/52637275/135322916-a017e346-8c82-4f23-a418-06df726f6832.png">
fig 4. booted without wallet, working (through a proxy), right after creating a wallet

---

I see an unnecessary placeholder in figures 1, 2, 3; filled in figure 4.

I would have a look at the code. I wonder if this is one of those QT
snake pit issues, like that one about not showing capslock active
until an alphabetic character is pressed. It's suspicious this is not
dealed with.

**Comment by hebasto** [comment]
@katesalazar 

Fixed in #439.

**Comment by katesalazar** [comment]
Oh, sweet. Will watch it right away. Thanks. ❤️

**Comment by katesalazar** [comment]
> FWIW, the relevant code is here

That was inviting, and I suppose I should have been able to
figure this one out, but I'm swamped real deep with
another PR and specially a couple tons of
non-work life stuff. 😭

I think that in around 5 to 7 years I'll be more free to tinker in
the bitcoin landscape.

Meanwhile, I hope I keep reporting GUI sightings (and test
the QML fork),
cheers.

**Comment by jarolrod** [comment]
I was able to replicate the bug when starting with no wallet
<img width="87" alt="Screen Shot 2021-09-29 at 9 15 46 PM" src="https://user-images.githubusercontent.com/23396902/135369791-c01c1b4f-4dda-4c73-bc82-3f2abb2d790b.png">
