### ISSUE TITLE
Separator can be omitted when adding third-party link actions to the transaction table

### ISSUE THREAD

**Issue by jarolrod** [bitcoin-core/gui#431]
[#4092](https://github.com/bitcoin/bitcoin/pull/4092) added the ability to add third-party links to block explorers and the functionality to show a selected translation in that block explorer. As stated in a review in that PR, it is important that we separate these third-party links from all of the other context-menu actions.
> "Nit: please add a menu separator between the 'normal' actions and the 'third party' actions."

Since the merge of that PR, there has been a bug where it's possible that this separator does not get added, and the third-party link actions merge in with our "normal" actions.

Because the addition of the separator is conditional on being at 0, if the first string passed is empty; then the separator will never get added. Now that we've iterated past 0, any subsequent actions will get merged in with our normal actions instead of being visually separated into its distinct section.

**To Replicate:**
1. Pass in arguments to the `Options->Display->Third party transaction URLs` menu setting that would result in the first string being empty. Example: `| | https://mempool.space/tx/%s | https://blockstream.info/tx/%s`.
2. Restart, navigate to Transaction window and right-click on a transaction.
3. Notice that any third-party links you had passed are now actions that have merged in with "normal" actions.

**Comment by jarolrod** [comment]
Went ahead and [pushed a commit](https://github.com/bitcoin-core/gui/pull/430/commits/8177578b296adb82fb8ab6c64cd76b832ebcc132) to #430 that will fix this.

**Comment by hebasto** [comment]
> Since the merge of that PR, there has been a bug where it's possible that this separator does not get added, and the third-party link actions merge in with our "normal" actions.
> 
> Because the addition of the separator is conditional on being at 0, if the first string passed is empty; then the separator will never get added. Now that we've iterated past 0, any subsequent actions will get merged in with our normal actions instead of being visually separated into its distinct section.

I can reproduce it:

![Screenshot from 2021-09-29 12-51-36](https://user-images.githubusercontent.com/32963518/135245939-4f6f5171-d9b4-4919-ba3a-3d34db551d7c.png)
