### ISSUE TITLE
Create a 'UI/UX' label for GUI related design issues

### ISSUE THREAD

**Issue by Bosch-0** [bitcoin-core/gui#44]
With initiatives such as [Bitcoin Design](https://github.com/BitcoinDesign) and [square crypto grants](https://medium.com/@squarecrypto/bringing-together-the-bitcoin-design-community-b89e5fbe080f) being offered for Bitcoin designers, I think its important to have a UI/UX label for the likely new wave of designers entering the space in the coming years.

Design does not mean a 'fancy GUI', but a more usable and intuitive GUI. Good design means good usability, good usability is security.

**Comment by laanwj** [comment]
Concept ACK however the whole repository is called "gui", I don't hink having a UI/UX label is good UX :smile: . Maybe just "Design"?

**Comment by Bosch-0** [comment]
A lot of repos use UI/UX as their standard design label but just design is also fine.

This might be a noob question but what does ACK mean ;D

**Comment by Bosch-0** [comment]
Design could relate to technical design whereas UI/UX is more specific, I don't see how its a bad label?

This might be a noob question but what does ACK mean? ;)

**Comment by laanwj** [comment]
> This might be a noob question but what does ACK mean? ;)

See here https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md#peer-review

**Comment by jonatack** [comment]
> This might be a noob question but what does ACK mean? ;)

See https://jonatack.github.io/articles/how-to-review-pull-requests-in-bitcoin-core#terminology
