### ISSUE TITLE
No obvious way to close peer detail panel

### ISSUE THREAD

**Issue by rebroad** [bitcoin-core/gui#485]
When clicking on a peer in the peer table, a panel is displayed, but there seems to be no obvious way to close this once opened.

**Comment by shaavan** [comment]
We could close the panel by clicking in the empty area. Though it's not immediately apparent, I don't think it's a bug per se.

**Comment by jarolrod** [comment]
you could make the splitter have dual functionality by adding in an arrow that would be a button, like so:

```
|    
|    # splitter functionality: resize
|
>   # Close the pane
|
|    # splitter functionality: resize
|
```

**Comment by RandyMcMillan** [comment]
I was thinking about this recently - I will post something.
