### ISSUE TITLE
Warning: Skipping -wallet path that doesn't exist. Failed to load database path '/home/$$$$/.bitcoin/wallets/!!!!!'. Path does not exist.

### ISSUE THREAD

**Issue by TheGabelKeith77** [bitcoin-core/gui#495]
Hello,

I've created more than a wallet for security reasons and moved the folder that contained the wallet.dat and other files into another place.

Now whenever I run Bitcoin Core GUI, I get the beneath error for (every) wallet created

Warning: Skipping -wallet path that doesn't exist. Failed to load database path '/home/$$$$/.bitcoin/wallets/!!!!!'. Path does not exist.

I replaced sensitive info. with $$$$ and !!!!

How can I stop Bitcoin Core from displaying this warning and ignore it ?

Thanks.

**Comment by hebasto** [comment]
Remove the according line from the `settings.json` file.

**Comment by TheGabelKeith77** [comment]
@jarolrod I didn't try it yet but I feel confident about it, so for now I think it's OK to close the question.

Thank you @hebasto and sorry for being late in reply.

Thank you @jarolrod as well.
