### ISSUE TITLE
[meta] GUI repo Questions and Feedback

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin-core/gui#5]
This is a thread for general meta questions and feedback regarding this repo

**Comment by hebasto** [comment]
Should we move the "x86_64 Linux [GOAL: install] [focal] [depends, sanitizers: thread (TSan), no gui]" CI job from Travis to Cirrus to avoid timeouts?

**Comment by hebasto** [comment]
Now we have timeouts on macOS native builds on Travis.

**Comment by hebasto** [comment]
> Now we have timeouts on macOS native builds on Travis.

Fixed in https://github.com/bitcoin/bitcoin/pull/19495.

**Comment by michaelfolkson** [comment]
@GBKS would like to get a commit stream/activity from this GUI repo on the Bitcoin Design Slack like there is on the Bitcoin Core Community Slack for the Core [repo](https://github.com/bitcoin/bitcoin). The Slack app must have been [installed](https://github.com/integrations/slack/issues/454#issuecomment-373038982) on the bitcoin organization but may not be installed for the bitcoin-core organization. Any of the owners of this GUI repo able to look into installing it so the Bitcoin Design Slack can get notifications on new PRs and Issues opened on this GUI repo?

**Comment by MarcoFalke** [comment]
Should be possible. All that is needed is the details that need to go into https://github.com/ owner / repo /settings/hooks/new

**Comment by michaelfolkson** [comment]
I think the next required step is an owner of this repo signs up to the Bitcoin Design [Slack](http://www.bitcoindesigners.org/), goes to the bitcoin-core-gui-pr-review channel and then inputs `/github subscribe bitcoin-core/gui` in that Slack channel.

**Comment by michaelfolkson** [comment]
That or an owner of this repo tries https://bitcoindesign.slack.com/ as the payload URL on that Add web hook page. That seems to be the only required field to get it working.

**Comment by MarcoFalke** [comment]
Should be connected now

**Comment by michaelfolkson** [comment]
Yeah works. Thanks @MarcoFalke! We'll keep this Issue open for further meta questions and feedback

**Comment by hebasto** [comment]
> Yeah works. Thanks @MarcoFalke! We'll keep this Issue open for further meta questions and feedback

Could merging notifications be excluded as they mostly are non-GUI ?
Details are available in https://bitcoindesign.slack.com/ discussion.

**Comment by hebasto** [comment]
@MarcoFalke Is it possible to receive "rebase needed" notifications for pulls in this repo? (e.g., #20)

**Comment by MarcoFalke** [comment]
Sure. See `/github help` and https://github.com/integrations/slack#configuration

**Comment by hebasto** [comment]
@MarcoFalke May I ask for adding "Linux" and "Tests" labels to the repo?

**Comment by fanquake** [comment]
> May I ask for adding "Linux" and "Tests" labels to the repo?

Added

**Comment by MarcoFalke** [comment]
Closing for now. If there are any new issues, please open a new issue.
