### ISSUE TITLE
QRCode address in image is not readable

### ISSUE THREAD

**Issue by fanquake** [bitcoin-core/gui#54]
Moved from: https://github.com/bitcoin/bitcoin/issues/19103.

Somehow the resolution of the QRCode image is not high enough.
Native wpkh addresses are non readable and legacy/p2sh addresses are not good readable.
Haven't tested on other OSes than macOS.

<img width="599" alt="Bildschirmfoto 2020-05-29 um 09 52 07" src="https://user-images.githubusercontent.com/178464/83235531-55807300-a192-11ea-8c5c-0f88481ecad1.png">

<img width="599" alt="Bildschirmfoto 2020-05-29 um 09 53 21" src="https://user-images.githubusercontent.com/178464/83235524-51ecec00-a192-11ea-8cb3-bcd580724be6.png">

**Comment by Bosch-0** [comment]
Same on Windows

![image](https://user-images.githubusercontent.com/55287964/90276413-70f84180-de96-11ea-8a77-9dbb5e725dc7.png)

Not as bad on Linux but could be better

![image](https://user-images.githubusercontent.com/55287964/90276522-a1d87680-de96-11ea-8906-be4b3954f2c8.png)

**Comment by Sjors** [comment]
Yikes, this looks like a regression; I remember it being far better. Able to reproduce on master on macOS.

**Comment by hebasto** [comment]
@Sjors 
> Yikes, this looks like a regression; I remember it being far better. Able to reproduce on master on macOS.

Could you point at a version with a nice look?
