### ISSUE TITLE
Mac OS keeps deleting Bitcoin Core GUI

### ISSUE THREAD

**Issue by surak** [bitcoin-core/gui#541]
I would expect the Bitcoin-QT client to stay on my machine, not to have to reinstall it every time.

It "disappears" - probably Mac OS' XProtect finds something it doesn't like in it and silently removes it

To reproduce: Have Bitcoin Core copied into the /Applications and wait some days

0.21.x, downloaded from Bitcoin.org

Mac OS 12.2, Macbook pro 16, 2019 model 

It doesn't keep log files anymore unless you have it set on the console app. I am not sure when it does this virus check.

**Comment by RandyMcMillan** [comment]
@Apple has become very invasive the last decade+ . I currently have the System Integrity Protection disabled - I am not sure if by default it is bypassing this functionality? I will try to look further into this. (I may have some other setting that has disabled this) - I will try to reproduce this.

**Comment by katesalazar** [comment]
Why is important to have it under /Applications?

It can be elsewhere and, if indexed,
spotlight is gonna find it anyway.

**Comment by hebasto** [comment]
I guess it is the same as bitcoin/bitcoin#23134. Therefore, closing.

Feel free to re-open this issue, if it differs from the one mentioned above.
