### ISSUE TITLE
Indicate network in the Node window title - similar to the main window

### ISSUE THREAD

**Issue by RandyMcMillan** [bitcoin-core/gui#544]
While testing/reviewing PR https://github.com/bitcoin-core/gui/pull/414

I was running Bitcoin-Qt.app concurrently with different active networks.
I noticed that it may be useful to indicate the network in the Node window title - similar to the main window title.
Additionally you can see that the task bar ornaments are crowded when the main window is minimized.
When the proxy setting is enabled - the "P" adds to the crowding.

NOTE: it may be useful to modify the global styling template based on network selected.
Adding an appropriate background color tint to the gui may be a good fix as well as the title modification.

 ![Screen Shot 2022-02-08 at 1 00 02 PM](https://user-images.githubusercontent.com/152159/153055744-363f1f0c-730c-4992-a7b6-5bc450d23897.png)

![Screen Shot 2022-02-08 at 1 47 58 PM](https://user-images.githubusercontent.com/152159/153055766-aee12444-029d-4e72-9eeb-0a7725065458.png)

**Comment by RandyMcMillan** [comment]
Commands to reproduce on MacOS

```
open -n "./Bitcoin-Qt.app" --args "-chain=main"
open -n "./Bitcoin-Qt.app" --args "-chain=test"
open -n "./Bitcoin-Qt.app" --args "-chain=regtest"
open -n "./Bitcoin-Qt.app" --args "-chain=signet"
```

**Comment by pablomartin4btc** [comment]
> Additionally you can see that the task bar ornaments are crowded when the main window is minimized.
> When the proxy setting is enabled - the "P" adds to the crowding.

This is not happening for me, at least in Ubuntu and Windows.
