### ISSUE TITLE
External signer Send button disabled

### ISSUE THREAD

**Issue by Sjors** [bitcoin-core/gui#551]
When using an external signer, the Create Unsigned button actually signs on the hardware device and the Send button is incorrectly disabled. Probably a regression from #441.

<img width="486" alt="Schermafbeelding 2022-02-18 om 17 27 00" src="https://user-images.githubusercontent.com/10217/154731834-b3371eda-1988-4c2b-b7f0-75440e6c1fe1.png">

cc @achow101

**Comment by Sjors** [comment]
(I took the liberty of assigning it 23.0 since it's a regression, cc @hebasto)

**Comment by hebasto** [comment]
For me pressing the "Create Unsigned" works as signing _and_ send.

What correct behavior is expected?

**Comment by Sjors** [comment]
> For me pressing the "Create Unsigned" works as signing and send.

That's both incorrect and confusing. It means the user can't make a PSBT if they want to, and they might think the wallet is broken because "Send" is disabled.

I think for external signers both buttons should be enabled, and the Create Unsigned should create a PSBT for the clipboard, not sign on the device.

**Comment by kristapsk** [comment]
Agree with @Sjors.
