### ISSUE TITLE
Display "local addresses" in "Node window"

### ISSUE THREAD

**Issue by kristapsk** [bitcoin-core/gui#564]
**Is your feature request related to a problem? Please describe.**
In command line you can run `bitcoin-cli -netinfo` to get local addresses node is listening for incoming connections. Would be useful to see this in GUI too, likely under "Information" tab of "Node window".

**Describe the solution you'd like**
Display local addresses in "Node window" under "Information" tab.

**Describe alternatives you've considered**
Only alternative is to run `getnetworkinfo` in console, which has a lot of additional output and is not user friendly.

**Comment by Jamewood** [comment]
[bitcoin-core/gui] Display "local addresses" in "Node window" (Issue #564)
