### ISSUE TITLE
Replace `QRegExp` with `QRegularExpression`

### ISSUE THREAD

**Issue by hebasto** [bitcoin-core/gui#578]
[`QRegularExpression`](https://doc.qt.io/qt-5/qregularexpression.html)
> implements Perl-compatible regular expressions. It fully supports Unicode.

[`QRegExp`](https://doc.qt.io/qt-5/qregexp.html)
> is modeled on Perl's regexp language. It fully supports Unicode.

> ... the new `QRegularExpression` class ... is recommended in place of `QRegExp`.

The most valued benefit will come when [migrating](https://github.com/bitcoin/bitcoin/pull/24798) to Qt 6, where [`QRegExp`](https://doc.qt.io/qt-6/qregexp.html) requires usage of an additional `Core5Compat` module.

Instead, all use cases of `QRegExp` could be [ported](https://doc.qt.io/qt-6/qregexp.html#porting-to-qregularexpression) to `QRegularExpression`.

#### Useful skills:

basic C++, Qt, regular expressions

#### Want to work on this issue?

For guidance on contributing, please read [CONTRIBUTING.md](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md) before opening your pull request.

**Comment by prusnak** [comment]
PR in https://github.com/bitcoin-core/gui/pull/585
