### ISSUE TITLE
Updating 2021 to 2022 in the start screen on GUI

### ISSUE THREAD

**Issue by IMPranshu** [bitcoin-core/gui#616]
![image](https://user-images.githubusercontent.com/43396684/172902073-7d37d8ea-d6b1-446f-8bce-a8d73d08cbc6.png)

I noticed while starting the GUI that it is mentioned 2021 on the start screen of the GUI. I downloaded the latest version from the official website yesterday only.

**Expected behavior**
2009-2022

**Actual behavior**
2009-2021

**System information**
Windows 10 latest build.

**Comment by katesalazar** [comment]
@IMPranshu see
https://github.com/bitcoin/bitcoin/blob/d2e0c27e45abd802849e3bf6006f495fc6055adb/src/qt/splashscreen.cpp#L46

**Comment by IMPranshu** [comment]
> 2021 is when the release was made. Not the current time.

My bad sir, I didn't know that.
