### ISSUE TITLE
Persist "mask values" to prevent shoulder surfing

### ISSUE THREAD

**Issue by fanquake** [bitcoin-core/gui#652]
Current Behavior: "Mask values" mode is off each launch and must be manually re-enabled.
If a wallet loads on startup from settings.json this leaves user vulnerable to shoulder surfing.

Solution: This mode should persist across restarts of bitcoin-qt by being saved in Bitcoin-Qt.conf.
Exactly how nDisplayUnit=0 will persist the unit to show amounts in.

Expected Behavior: If I shutdown Bitcoin core with it on, I'd expect it to be on when I restart and vice versa.

Moved from: https://github.com/bitcoin/bitcoin/issues/25826.

**Comment by pablomartin4btc** [comment]
This has been worked on #701 and I've worked on a follow-up masking the transactions view on #708

**Comment by hernanmarino** [comment]
Since #701 was merged, i believe this issue can be closed, right ?  @fanquake
