### ISSUE TITLE
Bitcoin-Qt GUI is very unresponsive when something happens

### ISSUE THREAD

**Issue by kord1e** [bitcoin-core/gui#667]
During syncing, Bitcoin-qt GUI often gets completely unresponsive when it's doing something under the hood (I don't know what exactly). For example if you try to open a menu it may take tens of seconds or even minutes before the menu is opened, if you clicked when the software was doing that something.

This problem has existed for several years, are there any plans to improve the GUI? 
https://github.com/bitcoin/bitcoin/issues/10504

**Comment by hebasto** [comment]
Closing as we already have an issue which tracks the mentioned problem.
