### ISSUE TITLE
Update icon to fit macOS 11+ style

### ISSUE THREAD

**Issue by ystolzenburg** [bitcoin-core/gui#674]
Current Bitcoin Core icon does not fit into the rest of macOS since 11 Big Sur, it should be updated to an appropriate squircle.

<img width="674" alt="screenshot of macOS dock, highlighting the difference between native looking and bitcoin core icons" src="https://user-images.githubusercontent.com/46424671/194720243-32794f46-ba13-49ff-8c71-51de891ea04f.png">

**Comment by jarolrod** [comment]
Sorry, but this issue is out of scope for the project; this is the logo/icon that has been used and will continue to be used. I would say that it is not true that all macos apps adhere to the "squircle".

**Comment by hebasto** [comment]
> Current Bitcoin Core icon does not fit into the rest of macOS since 11 Big Sur

It fits its own style across all supported platforms.

cc @GBKS

**Comment by GBKS** [comment]
Is it possible to define different icons for different platforms? For the web, there are even [special tools](https://realfavicongenerator.net) to create all the different icons needed for all browsers and operating systems. Could we do the same for this application?

**Comment by hebasto** [comment]
> Is it possible to define different icons for different platforms?

The code in our codebase, which is related to a macOS Dock icon, is macOS-specific already.

**Comment by katesalazar** [comment]
call the mathematicians to prove that a circle is a more
legit squircle than that xcode icon over there in OP post

**Comment by ystolzenburg** [comment]
Would look silly with a bitcoin icon, but that's an extra "detail" to add on top of the regular squircle (or rounded rectangle):
<img width="743" alt="Bildschirmfoto 2022-10-14 um 20 24 33" src="https://user-images.githubusercontent.com/46424671/195915441-979e7c44-5c74-47a0-b86a-7ac0de457eb8.png">

**Comment by katesalazar** [comment]
I stand corrected

**Comment by Sjors** [comment]
Evernote uses a circle too:

<img width="96" alt="Scherm­afbeelding 2023-01-24 om 13 58 47" src="https://user-images.githubusercontent.com/10217/214297852-7d8ceff5-24bd-4c1d-913a-581883b9a438.png">

And Apple's own trash can isn't a squircle either:

<img width="115" alt="Scherm­afbeelding 2023-01-24 om 14 00 10" src="https://user-images.githubusercontent.com/10217/214298132-27c7b8b2-379e-4e7d-8377-4bfcc344dd79.png">

I suspect Apple will change their icon fashion faster than we can ever keep up with :-)

**Comment by angelday** [comment]
I believe this issue should be closed because bitcoin-core is not a first party UI to the Mac anyway (it uses Qt) therefore making the app icon conforming to the Human Interface Guidelines is kind of pointless.

To add to the discussion, according to Apple: "In macOS, app icons share a common set of visual attributes, including a rounded-rectangle shape, front-facing perspective, level position, and uniform drop shadow."

![Screenshot 2024-08-03 at 07 26 44](https://github.com/user-attachments/assets/65048df4-f609-40d6-98ab-a7d0f398ba0d)

https://developer.apple.com/design/human-interface-guidelines/app-icons
