### ISSUE TITLE
Option to use dark theme

### ISSUE THREAD

**Issue by prayank23** [bitcoin-core/gui#68]
- I understand priority is to keep things simple and secure however some users prefer dark theme.

- Dynamically change the theme to either light or dark.

- Almost every bitcoin wallet for desktop has dark theme.

- Those pictures are looking good: https://github.com/bitcoin/bitcoin/issues/9639
- Did some research related to light/dark theme and qt although I am not the best person to suggest code related to design: https://github.com/Alexhuszagh/BreezeStyleSheets

**Comment by goums** [comment]
I'm using Dark mode on self compiled GUI, thanks to the tips shared by @jonatack 

I confirm, @Bosch-0 comment:
> > The GUI suffers from visual glitches in the new MacOS dark mode.

I've found two main UI glitches:
1. Icons stay in black on dark background:
![image](https://user-images.githubusercontent.com/5577626/101904802-b3b4f680-3bb6-11eb-8ee0-b4f26818db10.png)

2. Tabs focus and separator (in blue) are not clean:
![image](https://user-images.githubusercontent.com/5577626/101904778-a5ff7100-3bb6-11eb-881c-5b4f3d25f25f.png)
 
Otherwise, the dark mode seems pretty OK on macOS Big Sur.

I'll try to make PR to address the 2 issues above, if you think of any other glitches, let me know.

**Comment by prusnak** [comment]
It seems that using https://github.com/ColinDuquesnoy/QDarkStyleSheet might resolve most of the visual issues.

Switching to dark mode in macOS, Qt will trigger an event of the type `QEvent.PaletteChange` which can be detected and actioned upon in the main widget's `changeEvent` method.

**Comment by goums** [comment]
@prusnak for now, the GUI is not using any self defined palette, it inherits the OS color palette.

We could force our own light / dark palette, but that will be a bigger change, and might involve some UI designers.

My idea was to keep the current system as it is, but just fix the 2/3 glitches that occur on mac OS dark mode.
It should be easier to integrate in the codebase.

**Comment by goums** [comment]
@prusnak I've tried to play with QPalette and styleSheet to fix the display glitches, but it's not working because the bugs are directly in QMacStyle definition.

One solution could be to use the embedded QT style `fusion` which requires no dependencies, and support Light / Dark mode out of the box.
See my comment with screenshots on this related issue: https://github.com/bitcoin-core/gui/issues/136#issuecomment-748109959

**Comment by prayank23** [comment]
I was reading https://github.com/bitcoin-core/bitcoin-devwiki/wiki/0.21-Release-Candidate-Testing-Guide and it has dark mode screenshots

So do we already have dark theme in bitcoin core gui?

**Comment by goums** [comment]
@prayank23
currently, QT inherits from OS theme, so it depends on your OS, you can have dark mode on linux distributions.
on macos, it has been disabled because of the many glitches that were detected

> I was reading https://github.com/bitcoin-core/bitcoin-devwiki/wiki/0.21-Release-Candidate-Testing-Guide and it has dark mode screenshots

I think this is linux platform screenshots

**Comment by prayank23** [comment]
> It seems that using https://github.com/ColinDuquesnoy/QDarkStyleSheet might resolve most of the visual issues.

@prusnak I tried following the steps mentioned in [README.rst](https://github.com/ColinDuquesnoy/QDarkStyleSheet/blob/master/README.rst) but getting error when I launch `bitcoin-qt`

Steps that I followed:

1. Clone https://github.com/ColinDuquesnoy/QDarkStyleSheet.git
2. Copy `qdarkstyle/style.qss` and `qdarkstyle/style.qrc` in `src/qt`
3. Add path for `style.qrc` in `contrib/bitcoin-qt.pro`

```
RESOURCES += \
    ../src/qt/bitcoin.qrc
    ../src/qt/style.qrc
```
4. Add below code in `src/qt/bitcoingui.cpp`:

```
QFile f(":/home/satoshi/bitcoin/src/qt/style.qss");

if (!f.exists())   {
    printf("Unable to set stylesheet, file not found\n");
}
else   {
    f.open(QFile::ReadOnly | QFile::Text);
    QTextStream ts(&f);
    qApp->setStyleSheet(ts.readAll());
}
```
5. Launch `bitcoin-qt`

Error: `Unable to set stylesheet, file not found`

![image](https://user-images.githubusercontent.com/13405205/110535478-56ddc380-8146-11eb-821d-073966f47809.png)

**Comment by jarolrod** [comment]
@prayank23 on Ubuntu/Debian (as your screenshot suggests you are using), just set a dark GTK theme.

**Comment by prayank23** [comment]
@jarolrod I understand the workaround as jonatack had shared links when I created this issue. I am trying to add option in Bitcoin Core to switch light/dark theme which can work on all platforms irrespective of OS settings.

**Comment by jarolrod** [comment]
@prayank23 I see, you'd need to come up with a stylesheet for both (light + dark) I believe. Maybe in talks with the design community. And you can add a toggle button somewhere in the menu.

**Comment by prayank23** [comment]
Its working :) Suggestion by @hebasto in IRC channel ##bitcoincore-gui helped. Had to remove `:` from `QFile f(":/home/satoshi/bitcoin/src/qt/style.qss");`

There are few things that will need to be changed or added. Screenshots:

![image](https://user-images.githubusercontent.com/13405205/112693105-0a181d80-8ea6-11eb-89fd-18a2f54d8a72.png)


![image](https://user-images.githubusercontent.com/13405205/112693155-274cec00-8ea6-11eb-8d4c-5781f9f46076.png)


![image](https://user-images.githubusercontent.com/13405205/112693254-55323080-8ea6-11eb-8cb4-2a961f871bd0.png)


![image](https://user-images.githubusercontent.com/13405205/112693695-13ee5080-8ea7-11eb-892b-db107553e5a4.png)


![image](https://user-images.githubusercontent.com/13405205/112693765-2bc5d480-8ea7-11eb-886d-e1ae78c5c098.png)


![image](https://user-images.githubusercontent.com/13405205/112693478-b35f1380-8ea6-11eb-887a-0a830b67d664.png)


Splash screen still remains the same:

![image](https://user-images.githubusercontent.com/13405205/112693382-8c084680-8ea6-11eb-819b-8b4e9e246db4.png)

**Comment by prayank23** [comment]
This does not work on Windows as expected

**Comment by hebasto** [comment]
After #366 is merged the Bitcoin Core GUI should follow system appearance settings. It works on macOS. Also it works on some DEs on Linux. Not sure if anybody test the current master on Windows, though.

Going to close this issue. Feel free to open a new platform or DE specific one.
