### ISSUE TITLE
Confusion with Create Wallet menu options

### ISSUE THREAD

**Issue by Rspigler** [bitcoin-core/gui#69]
This is in regards to https://github.com/bitcoin/bitcoin/pull/15450

If you check 'Disable Private Keys', is that not initially a Blank Wallet, until you import an xpub?
I don't understand what the difference would be between checking just 'Disable Private Keys', and checking 'Disable Private Keys' and 'Make Blank Wallet'.

Should checking 'Disable Private Keys' automatically check 'Make Blank Wallet'? (But not vice versa - Making a Blank Wallet with/without Disabling Private Keys affects the future ability to import.)

But then I am concerned that this would be very confusing for the end user.  Enabling 'Encrypt Wallet' already disables 'Disable Private Keys'.

**Comment by Rspigler** [comment]
I like that a lot! (I had some difficulty in opening this in a DispVM, maybe paste screenshots/code here for people who don't want to leave github to review?)

Some typos in the 'Blank Wallet' descriptions; example "A blank wallet has will generate..."

In the 1.2 modal; are you able to click more than one wallet option? Should selecting one, grey out the others?

**Comment by Rspigler** [comment]
Referencing this here:
https://github.com/bitcoin/bitcoin/pull/17879#issuecomment-578533079

**Comment by Bosch-0** [comment]
I'll upload a screenshot once I have made some changes - though there are many UI/UX changes being made other than just the initial menu options so ill likely open a new issue. 

Fixed that typo cheers, no spellcheck on Figma - usually clean up those details at the end ;)

**Comment by prayank23** [comment]
> I've got a WIP design related to this issue that more clearly explains each option, you can view it here: https://www.figma.com/file/FJ02rY3m8V9ZCDvoXjW39W/Bitcoin-Core?node-id=281%3A0

 @Bosch-0 This looks good.

![screenshot](https://i.imgur.com/HV6zEiU.jpg)
