### ISSUE TITLE
View JPEG-encoded data

### ISSUE THREAD

**Issue by speedybonder** [bitcoin-core/gui#707]
I set up a node to view transactions containing JPEG image data, however I am only able to see some other details about the transactions even when the JPEG is present rather than the JPEG itself.

Implementing an JPEG viewer, or even an general media player for other types of content, would make the process of viewing rich media stored on-chain much more simpler.

I am not a particularly technical person, but VLC player is good for video and songs, so that may be a good starting point. For images, I am not so sure of what is out there.

**Comment by jonatack** [comment]
I am not sure whether a built-in JPEG viewer is relevant to this wallet software, but it seems you may already view those on mainnet at [ordinals.com](https://ordinals.com/) and on signet at [signet.ordinals.com](https://signet.ordinals.com/).

**Comment by hernanmarino** [comment]
I definitely disagree on adding this feature.
