### ISSUE TITLE
Error opening bitcoin core app: Error: Prune mode is incompatible with -txindex.

### ISSUE THREAD

**Issue by joyqvq** [bitcoin-core/gui#715]
I downloaded bitcoin core had synced my node last week. I quit the bitcoin core and reopens, the app shows this error: 

```Error: Prune mode is incompatible with -txindex.```

 <img width="488" alt="image" src="https://user-images.githubusercontent.com/108701016/221428605-611c9a8d-63e8-45f6-9661-c72b6eb72cba.png">

When I click OK, the app quits. I am using: 

Chip: Apple M1 Max
macOS: 13.1 (22C65)

**Comment by pinheadmz** [comment]
Did you change any settings or write a bitcoin.conf at any point ?

**Comment by joyqvq** [comment]
yes you are right! i changed it to `txindex=1`... removing it works. thanks for the help!

**Comment by fanquake** [comment]
Note that the latest available version of Bitcoin Core is 24.0.1 (you are running 22.0.0). You can download the latest version from bitcoincore.org.
