### ISSUE TITLE
guiutil.cpp: formatNiceTimeOffset

### ISSUE THREAD

**Issue by Sataur** [bitcoin-core/gui#728]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

_last received block was generated _ years and 0 weeks.._

### Expected behaviour

that tool tip can be improved by:
_..you first see the [raw](https://4sysops.com/archives/format-time-and-date-output-of-powershell-new-timespan/) output and then the human-friendly version created by my.._
_Only non-zero weeks, days, hours, minutes and seconds are displayed_

### Steps to reproduce

_Submit a new bug report. If this doesn’t look right, [choose a different type.](https://github.com/bitcoin-core/gui/issues/new/choose)_

https://github.com/bitcoin-core/gui/issues/new?assignees=&labels=GUI&projects=&template=gui_issue.yml

_Issues, reports or feature requests related to the GUI should be opened directly on the GUI repo_

### How did you obtain Bitcoin Core

Pre-built binaries

### What version of Bitcoin Core are you using?

v24.0.1

### Operating system and version

Win11

### Machine specifications

n/a

**Comment by RandyMcMillan** [comment]
Please post a screen shot - for clarity.

**Comment by hebasto** [comment]
Closing for now.

> Please post a screen shot - for clarity.

Can be reopened when more details (a screenshot) will be provided.

> that tool tip can be improved

It is still not clear what is wrong with the current implementation.
