### ISSUE TITLE
Can't start bitcoin-qt by double-click on Debian 11

### ISSUE THREAD

**Issue by hebasto** [bitcoin-core/gui#730]
Moved from https://github.com/bitcoin/bitcoin/issues/27655.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

When I double-click the bitcoin-qt executable file in the graphical file manager, Bitcoin Core doesn't start and this message pops up:

![Screenshot from 2023-05-13 10-39-57](https://github.com/bitcoin/bitcoin/assets/1530071/a0e956e3-7a13-4288-a7fc-96738667c63c)

I think this issue is the same as described at https://fostips.com/double-click-run-elf-ubuntu/
The Bitcoin Core build process seems to set some properties on the ELF file so that Debian 11 thinks the file has mime type `application/x-sharedlib`, and the file is thus treated as a shared library file. For Bitcoin Core 0.8.6, on the other hand Debian 11 shows the mime type to be `application/x-executable`, and I'm able to start it by double-clicking it. The workaround mentioned in the link above makes modern Bitcoin Core versions double-clickable.

Yes, the file has the executable flag set:

```
$ ls -l
total 95944
-rwxr-xr-x 1 demo demo  2412928 dec  6 16:53 bitcoin-cli
-rwxr-xr-x 1 demo demo 15339968 dec  6 16:53 bitcoind
-rwxr-xr-x 1 demo demo 39586776 dec  6 16:53 bitcoin-qt
-rwxr-xr-x 1 demo demo  4112824 dec  6 16:53 bitcoin-tx
-rwxr-xr-x 1 demo demo  2199488 dec  6 16:53 bitcoin-util
-rwxr-xr-x 1 demo demo  9686216 dec  6 16:53 bitcoin-wallet
-rwxr-xr-x 1 demo demo 24893312 dec  6 16:53 test_bitcoin
```

### Expected behaviour

I expected Bitcoin Core to start in GUI mode

### Steps to reproduce

Download bitcoin-24.0.1-x86_64-linux-gnu.tar.gz and unpack it. In the graphical file manager, I navigate to the bin folder and double-click on the bitcoin-qt file.

I tried also version 0.18.1, 0.20.0,  22.1 which all behaved the same.

I tried ancient version 0.8.6 and it worked as I would expect.

### How did you obtain Bitcoin Core

Pre-built binaries

### What version of Bitcoin Core are you using?

v24.0.1

### Operating system and version

Debian 11

### Machine specifications

x86_64

**Comment by hebasto** [comment]
We've discussed this with @kallerosenbaum offline and decided to close this issue as a system-specific one and having the workaround pointed out in https://github.com/bitcoin/bitcoin/issues/27655#issue-1708983426.

**Comment by kallerosenbaum** [comment]
Thanks @hebasto 

Since Ubuntu is based on "Debian Testing", and the current ubuntu LTS works, I'm guessing (I haven't tested this issue on Debian Testing so I don't really know this) this issue will be resolved in the next major version of debian.

**Comment by kallerosenbaum** [comment]
Oh, I didn't know Debian 12 just dropped yesterday. Will give it a try and post the result here.

**Comment by kallerosenbaum** [comment]
@MarcoFalke I just upgraded to Debian 12, and it works fine here. Good stuff.
