### ISSUE TITLE
Help '?' button on create wallet and encrypt wallet modals does nothing

### ISSUE THREAD

**Issue by Bosch-0** [bitcoin-core/gui#74]
The help button '?' on the create wallet modal (and the following encrypt wallet modal) does not do anything on WindowsOS. This does not exist on the Linux version, have not tested Mac.

![image](https://user-images.githubusercontent.com/55287964/91263083-d1df1e00-e7a2-11ea-8a6d-0b51c2bfa8d8.png)

**Comment by hebasto** [comment]
Remove it on all platforms or make it to do something on all platforms?

**Comment by Bosch-0** [comment]
Where was it suppose to direct the user to?

**Comment by achow101** [comment]
Since it does nothing, it's reasonable to say we should remove it. I don't think there was any intention to have that button there.

**Comment by hebasto** [comment]
Fixed in #85.
