### ISSUE TITLE
Address book page window (receiving or sending) should display the wallet name on its title

### ISSUE THREAD

**Issue by pablomartin4btc** [bitcoin-core/gui#756]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

At the moment, when a user has multiple wallets loaded and switches between them while opening the Address Book manager to check or copy "Sending" or "Receiving" addresses, it's not clear which addresses belong to which wallet.

![image](https://github.com/bitcoin-core/gui/assets/110166421/521ffe14-dcbd-41b5-ad5b-51f9ceb6a7f7)

### Expected behaviour

Similar to the main window, I think the address book page window should point out to which wallet those addresses belong to.

### Steps to reproduce

1. Launch the `bitcoin-qt` application on any network.
2. Ensure you have at least two wallets loaded. If needed, create additional wallets.
3. Open the "Receiving addresses" (or "Sending...") window from the "Windows" menu at the top.
4. Select a different wallet from the combo-box labeled "Wallet:" in the main application window.
5. Once again, go to the "Windows" menu and select "Receiving addresses" (or "Sending..." depends on step 3).

This sequence of steps will open separate "Receiving addresses" (or "Sending...", depends on steps 3 & 5) windows with distinct lists of addresses. To create "receiving addresses," click the "Receive" button located under the main menu at the top, which will open the receive coins dialog.

### How did you obtain Bitcoin Core

Compiled from source

### What version of Bitcoin Core are you using?

v25.99

### Operating system and version

Ubuntu 22.04

**Comment by jarolrod** [comment]
Concept ACK, This can be useful, removing any possible confusion
