### ISSUE TITLE
Remove BDB checkbox in wallet creation dialog

### ISSUE THREAD

**Issue by maflcko** [bitcoin-core/gui#763]
### Please describe the feature you'd like to see added.

With BDB being removed soon, it seems confusing and harmful to allow users to create fresh BDB wallets going forward, as it would load them with an additional burden of having to migrate them soon after.

### Describe the solution you'd like

Remove BDB checkbox

### Please leave any additional context

Power users can still create BDB wallets in the meantime, if they really want to, with an older release, or in the RPC console.

**Comment by hebasto** [comment]
Concept ACK.

**Comment by furszy** [comment]
Could also only show the check box when the `deprecatedrpc=create_bdb` (https://github.com/bitcoin/bitcoin/pull/28597) is enabled.

**Comment by hebasto** [comment]
@furszy 

Want to submit a PR?

**Comment by Sjors** [comment]
Concept ACK

I also think people should use the RPC if the _really_ want a legacy wallet.
