### ISSUE TITLE
When using an unencrypted read-only wallet, pressing "Create Unsigned", shows "This operation needs you wallet passphrase to unlock the wallet"

### ISSUE THREAD

**Issue by stevenroose** [bitcoin-core/gui#772]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

When using an unencrypted, read-only (descriptor) wallet, when trying to make a new transaction and pressing the "Create Unsigned" button, a dialog is shown with the message "This operation needs you wallet passphrase to unlock the wallet". There is no wallet passphrase as I have never created it. It's also not possible to enter the empty passphrase as the submit button is grayed out.

### Expected behaviour

"Create Unsigned" creates an unsigned PSBT.

### Steps to reproduce

> When using an unencrypted, read-only (descriptor) wallet, when trying to make a new transaction and pressing the "Create Unsigned" button

### Relevant log output

no log output without debugging enabled

### How did you obtain Bitcoin Core

Package manager

### What version of Bitcoin Core are you using?

v25.1

### Operating system and version

Guix

**Comment by achow101** [comment]
Are you able to reproduce this on master?

I am unable to reproduce this issue. On regtest, I created a new wallet with private keys disabled and was able to use the "Create Unsigned" button as expected.

This is likely an issue specific to your wallet. Is it possible that you had used it with unreleased software or an unmerged PR? Would you be willing to share this wallet file?

**Comment by achow101** [comment]
If your watchonly was encrypted with an older version of Bitcoin Core that accidentally allowed that, then it is possible to hit this error. The obvious solution is to enter the password. If you don't remember it, and are feeling particularly adventurous, you can open the wallet.dat file with your choice of sqlite tool, find the record beginning with `\x04mkey`, and delete it.
