### ISSUE TITLE
Weird focus rect displayed on inital sync

### ISSUE THREAD

**Issue by ManuelSchneid3r** [bitcoin-core/gui#783]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

<img width="891" alt="Bildschirmfoto 2023-12-20 um 11 41 09" src="https://github.com/bitcoin-core/gui/assets/3252315/74c17ab2-460d-4eba-8151-3f19c35b71a7">

### Expected behaviour

<img width="866" alt="Bildschirmfoto 2023-12-20 um 11 43 55" src="https://github.com/bitcoin-core/gui/assets/3252315/7748c491-e0be-4f34-bb4e-c6e39f7c1244">

### Steps to reproduce

Start Bitcoin-Qt

### How did you obtain Bitcoin Core

Pre-built binaries

### What version of Bitcoin Core are you using?

Bitcoin Core Version v25.0.0

### Operating system and version

mac 13.6 (22G120)

**Comment by ManuelSchneid3r** [comment]
Just updated to 26. still there.

**Comment by jadijadi** [comment]
Tried to reproduce this on 26.9.9 with no successful. 
May I ask how you produced the "expected result" image? what do you do to "fix" the issue? And is there a way to "show/hide" the strange rectangular? I can see that in the problematic photo you have the Hide button focused too. Does losing the focus hides the strange highlight square?

**Comment by ManuelSchneid3r** [comment]
I just started it. yes Actually I deactivated the app to let the focus disappear.

**Comment by jadijadi** [comment]
Thanks for the explanation. I can reproduce and will work on it today.
