### ISSUE TITLE
When selecting a custom data directory on first launch of Bitcoin Core GUI on Mac, where is that setting stored?

### ISSUE THREAD

**Issue by so7ow** [bitcoin-core/gui#798]
### Issues, reports or feature requests related to the GUI should be opened directly on the GUI repo

- [X] I still think this issue should be opened here

### Report

When selecting a custom data directory on first launch of Bitcoin Core GUI on Mac, where is that setting stored?

I've looked in ~/Library/Application\ Support/Bitcoin for bitcoin.conf and settings.json and in the selected custom location for those same files and I can't locate where that configuration setting is stored.

**Comment by so7ow** [comment]
I belive I've located it:

`~/Library/Preferences/org.bitcoin.Bitcoin-Qt.plist`

**Comment by so7ow** [comment]
I spoke too soon. When I delete that file, Bitcoin Core GUI still knows about the custom location I selected at first launch.

**Comment by hebasto** [comment]
> I believe I've located it:
> 
> `~/Library/Preferences/org.bitcoin.Bitcoin-Qt.plist`

That's correct. Also see https://github.com/bitcoin-core/gui/blob/master/doc/files.md#gui-settings.

> I spoke too soon. When I delete that file, Bitcoin Core GUI still knows about the custom location I selected at first launch.

You have to invalidate the corresponding cache: https://stackoverflow.com/questions/19742452/qsettings-on-os-x-10-9-unable-to-locate-clear-it.

**Comment by so7ow** [comment]
Thank you! Confirmed this works:

```
rm ~/Library/Preferences/org.bitcoin.Bitcoin-Qt.plist
killall -u YourUserName cfprefsd
```
