### ISSUE TITLE
walletpassphrase (console mode) - Fails to consider comma as a valid passphrase character.

### ISSUE THREAD

**Issue by hemzer** [bitcoin-core/gui#80]
Try to unlock wallet in the console with command line walletpassphrase fails if a comma is contained in the passphrase. The json parser wont allow it.

**Expected behaviour**

Should accept comma as valid character part of the passphrase.

**Actual behaviour**

eg: Try command in console window
walletpassphrase  "km3k5h3lk,X$VG#$" 120

All the time.
eg: Try command in console window
walletpassphrase  "km3k5h3lk,X$VG#$" 120

core 0.20.0

Tails OS

Tails OS

**Comment by hebasto** [comment]
Tested current master -- works as expected.

@hemzer Do you mind trying v0.21 or master branch?

**Comment by hebasto** [comment]
Closing for now.
