### ISSUE TITLE
Segfault in qt/clientmodel.cpp:92 on every shutdown

### ISSUE THREAD

**Issue by maflcko** [bitcoin-core/gui#800]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

On shutdown, I get a crash in `return m_node.getNodeCount(connections);`

### Expected behaviour

No crash

### Steps to reproduce

* Shutdown Bitcoin Core

### How did you obtain Bitcoin Core

Compiled from source

### What version of Bitcoin Core are you using?

master

### Operating system and version

ubuntu

**Comment by furszy** [comment]
#801

**Comment by hebasto** [comment]
> #801

@maflcko Does it fix the issue for you?

**Comment by hebasto** [comment]
Closed by https://github.com/bitcoin-core/gui/pull/801.
