### ISSUE TITLE
Create unsigned when increasing fee asks for the passphrase

### ISSUE THREAD

**Issue by kohend** [bitcoin-core/gui#810]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

Trying to increase the fee on a pending transaction, creating a psbt is asking for the passphrase, though it shouldn't need to unlock the wallet to create a psbt (and didn't require when creating the initial transaction).

### Expected behaviour

Create the psbt without the need for unlocking the wallet

### Steps to reproduce

Locked wallet
Set PSBT actions to enabled in settings
create a transaction with a fee increase replacement option and send it
raise the fee
Choose create PSBT
Get prompt for wallet unlock

### How did you obtain Bitcoin Core

Package manager

### What version of Bitcoin Core are you using?

26.0.0.0

### Operating system and version

Ubuntu 22.04

**Comment by hebasto** [comment]
cc @achow101 @furszy

**Comment by kohend** [comment]
I doubt it matters, but I am using the flatpak version.

**Comment by kohend** [comment]
Wow, that was fast!

**Comment by pablomartin4btc** [comment]
@kohend are you able to test @furszy's fix?

**Comment by kohend** [comment]
Yes, but it'll take a bit, since I have more urgent items in my queue.
