### ISSUE TITLE
Network tray icon should open peers window, add button to disable network there

### ISSUE THREAD

**Issue by Sjors** [bitcoin-core/gui#93]
I doubt many users are looking for a quick way to disable the network:
<img width="248" alt="Schermafbeelding 2020-09-16 om 13 56 57" src="https://user-images.githubusercontent.com/10217/93334019-83162880-f824-11ea-9ea1-f950f3392fe3.png">

More likely, at least from my experience, they want to see the list of peers.

I suggest linking this icon to the peers tab. And then add a button there to disable the network.

**Comment by hebasto** [comment]
@Sjors 

Do you mind checking out #309?
